### ISSUE TITLE
User management documentation

### ISSUE THREAD

**Issue by EruantalonJS** [verdaccio/verdaccio#105]
Hi,

Is there any documentation and / or recipes regarding user and group management in verdaccio? I haven't seen anything besides the basic "$authenticated" default group

**Comment by 0815fox** [comment]
I am seeing this as well. How can I make sure, that only users, which I added to a certain group can access packages from a certain scope?

**Comment by XavierBoubert** [comment]
👍

**Comment by juanpicado** [comment]
I think this depends of the plugin you set up, the build-in one is quite simple, it has no groups support https://github.com/verdaccio/verdaccio/blob/master/lib/plugins/htpasswd/index.js#L47 and seems in the next major release  #168 this will change . I won't document it now because it's gonna change anyway.  Please feel free to reopen if you considere is not enough information.
fyi:
http://resolvethis.com/how-to-create-a-new-sinopia-user/
https://yuyudhan.wordpress.com/2017/01/14/hosting-private-npm-repository-using-sinopia/

**Comment by juanpicado** [comment]
Guys, please let me know whether you are happy for the following documentation for packages accessing.

https://github.com/verdaccio/verdaccio/blob/d8177a772454c4a5234277b8801d36fa80a19cf4/wiki/packages.md
