### ISSUE TITLE
How add new user when registration is disabled

### ISSUE THREAD

**Issue by darkowic** [verdaccio/verdaccio#106]
As a admin I would like to know how to add new user while registration is disabled.

Currently I use workaround -> changing setting add adding new user...

Maybe executable `verdaccio` should have option for this?

**Comment by juanpicado** [comment]
Sorry, I don't know I if get it, but,  there is no roles, the machine user that runs verdaccio is the *admin*. When registration is disable there is no way to add more uses unless you change the config `max_users` value. See this line. (https://github.com/verdaccio/verdaccio/blob/master/lib/plugins/htpasswd/index.js#L62)

**Comment by 0815fox** [comment]
I found the following tip on [this page](https://github.com/rlidwka/sinopia-htpasswd).
```
echo "user:`mkpasswd --method=sha-512 password`" >> htpasswd
```
I will give it a try now.

**Comment by 0815fox** [comment]
It did not work. Also the strings generated by mkpasswd look much longer than those generated through the normal way.
```
foo:$6xx6LbdC2aqY:autocreated 2017-02-02T12:32:08.083Z
db:$6$cFgrPbyye4$tmyUvmd.g1JJdFJrs1pjNADU1MRY./fvXuYypUwaC1ftwIM8IUZvme69u9UsyKQz6JtWN8bAnjtlAb9R0q6a11
```
where foo is a test user as stored by verdaccio through npm login-registration-procedure and db is a test user generated with mkpasswd. Login does not work.
Can someone tell us exactly, which algorithm is used?
Also I saw, that two test users with the same password have the same hash -> is there one static salt?

**Comment by juanpicado** [comment]
@0815fox  I would not take `sinopia-htpasswd` as a reference, the code has evolved (https://github.com/verdaccio/verdaccio/commit/e45fe466eec54c8eab17a7c0b881832d2017542f#diff-4b93cde51ff144a99525e47cef2843e6) since the last commit in `sinopia`. In the past the plugin was bundled and is completely different.

I've been looking into the *algorithm* that we use is fairly simple and easy to reproduce. In simple steps this is the easy way to generate a password.

````javascript
var crypto = require('crypto');
var crypt = require('unix-crypt-td-js');
var user = 'foo';
var passwd = 'bar';
var salt = '$6$' + crypto.randomBytes(10).toString('base64');
var pass = crypt(passwd, salt);
var comment = 'autocreated ' + (new Date()).toJSON()
var newline = user + ':' + pass + ':' + comment + '\n';
console.log(newline);
// foo:$6xx6LbdC2aqY:autocreated 2017-02-02T21:22:18.148Z
````

Maybe It even make sense create a small cli :) . So in resume, **do not use mkpasswd** as reference.

**Comment by darkowic** [comment]
Cli command would be great
