### ISSUE TITLE
How install a public package like private package?

### ISSUE THREAD

**Issue by GibranLara** [verdaccio/verdaccio#1106]
**Describe the bug**
I already have Verdaccio installed correctly, now what I need is to install packages that are public but on the private server.

For example:

I need to have jQuery version 3.X.X on the private server. How do I install it?

Do I have to do the following?

1. Download the package in an empty project
2. Go to the root of the package.
3. Make a npm publish --registry http://localhost:4873 to my private server.

It is right?

**Update 1**.

I did the steps that I previously described and published jquery to the private registry and apparently it worked. It already appears in the list.
![captura](https://user-images.githubusercontent.com/22408615/48032769-89aec180-e11e-11e8-8648-b98eacaee356.PNG)

**Update 2.**

I was checking in the documentation https://verdaccio.org/docs/en/what-is-verdaccio.html#proxy that when a proxy is used, call npmjs, the packages that are not in the private registry download them from npmjs and also to the cache of verdaccio. But I noticed that the package that was not found in the private registry and was downloaded from npmjs is not registered as a private package, not in the .sinopia-db.json file and neither appears in the list of web interface packages. For example, I installed Request through the proxy, it is downloaded and installed correctly in the cache, but it is not registered as a private package.

**Expected behavior**
Install a public package like private.

**Comment by juanpicado** [comment]
https://github.com/verdaccio/verdaccio/issues/418
https://github.com/verdaccio/verdaccio/issues/706

**Comment by juanpicado** [comment]
You can create a package access section of that specific one and removing the proxy, so verdaccio will resolves the local one and never will fetch the public one.

**Comment by dekadentno** [comment]
> When it comes to uploading a package that has dependencies, and dependencies plus dependencies becomes crazy, you have to do the manual installation of each of them.

Have you found a solution for this problem? @GibranLara 
From my experience, there are some packages that require publishing each of their dependencies one at a time (but I haven't found out why this sometimes works out of the box and sometimes it doesn't).
What I wanted to say is that I had some projects for which I transferred all their dependencies to my private verdaccio registry, and after running npm install everything worked as expected.
Right now, I was transferring some packages to a private registry and some of them require to manually publish their own dependencies manually, one by one (and if I understood correctly, you had the same issue?).

If anyone has some sort of an idea how and why this happened, or is it some sort of a bug or this scenario happened because of my mistake, it would be very helpful.

(Sorry for bumping an old topic)

**Comment by GibranLara** [comment]
> Have you found a solution for this problem?

Unfortunately not @dekadentno .
