### ISSUE TITLE
Switch to TypeScript

### ISSUE THREAD

**Issue by stackdumper** [verdaccio/verdaccio#1166]
As for me, TypeScript is much more convenient and has better integrations for code editors. I believe switching to TS would allow Verdaccio to evolve faster and would encourage contributors and, especially, plugin developers.

**Comment by juanpicado** [comment]
We are working on it, first step https://github.com/verdaccio/verdaccio/pull/1164 
It won't happen soon. After release v4.

**Comment by juanpicado** [comment]
Working on this by steps

- [ ] migrate streams repo to Typescript (https://github.com/verdaccio/streams)
- [ ] WIP migrate verdaccio-memory repo to Typescript (https://github.com/verdaccio/verdaccio-memory)

**Comment by juanpicado** [comment]
✔️ List
- ✔️ Migrated all direct dependencies to Typescript
- ✔️ Created Types for Typescript
- ✔️ Using migrated dependencies on branch`4.x`

This is the most I can do. We cannot migrate the main project yet until `4.x` is merged into `master` otherwise we will block new contributions. After release, I will complete the remaining part.

**Comment by juanpicado** [comment]
Update: Migration is done, waiting possible code reviews. https://github.com/verdaccio/verdaccio/pull/1374
