### ISSUE TITLE
Docker Swarm => Exit Code 143 when stopped

### ISSUE THREAD

**Issue by xFragger** [verdaccio/verdaccio#1198]
**Describe the bug**
When running the image inside docker swarm, the container won't exit with code 0, but 143 instead, even with no errors or something in the log

**To Reproduce**
1. Start container in swarm
`docker service create --name verdaccio --mode replicated --replicas 1 --detach=false --rollback-order start-first --update-delay 10s --update-order start-first --update-failure-action rollback --mount type=bind,src=/mnt/nfs/docker-data/verdaccio,dst=/verdaccio verdaccio/verdaccio:latest`
2. Stop service `docker service rm verdaccio`
3. Look at `docker ps -a` of the node, where the image was running

**Expected behavior**
The container should shutdown gracefully and exit with code 1 or at least 137 if the gracefull shutdown was not possible and the container had to be killed with `kill -9`

**Docker || Kubernetes (please complete the following information):**
 - Docker verdaccio tag: latest (i think 3.10.1)
 - Docker Version 18.09.1

**Comment by exic** [comment]
As far as I understand, this is the expected behavior on swarm. You'd get exit code 0 if the process finished on its own (without docker service rm). Since docker swarm tells the process to end itself, the return code is 143 if it shut down was ok (128 + 15) and 137 if it failed to shut down in time (128 + 9), as you wrote.
See https://stackoverflow.com/questions/31297616/what-is-the-authoritative-list-of-docker-run-exit-codes and the links in the answers. I'm curious if you agree with my interpretation.
