### ISSUE TITLE
Auth plugin like FontAwesome

### ISSUE THREAD

**Issue by beadm** [verdaccio/verdaccio#1214]
I would like to create a plugin which authenticates the user before downloading a package. The idea is that the user receives a **unique access token** from our service (so it's different from the one that npm generates when the user logs in) and stores it into an _.npmrc_:

```
//npm.ourservice.com/:_authToken="UNIQUE-ACCESS-TOKEN"
```

Then when the user tries to install the package the plugin calls an external endpoint with this **unique access token** which verifies if the user can download the package or not. It's very similar to what FontAwesome achieved here:
https://fontawesome.com/how-to-use/on-the-web/setup/using-package-managers#installing-pro

I've spent a couple of hours trying to figure out how I could create such a plugin, but I just don't get it. I'm almost sure that I need to use a middleware, because an auth plugin can only access username/password combo, which is not good, because I'd need the `:_authToken` stored in _.npmrc_. What I don't seem to understand is when do these middleware plugins actually run. When I start `verdaccio` service the `register_middlewares()` method of the plugin is executed, but not when initiating `npm install {PLUGIN} --registry {REGISTRY}`. Also I don't seem to be able to access the `:_authToken` value.

Do you have any suggestion how should I get started with it?

**Comment by nphyatt** [comment]
@beadm I think that registering middleware is not enough because by the time the middleware runs token based authentication has already happened. I'm proposing a way to accomplish this in my PR #1227 where you can swap out the defualt token based auth middleware with custom middleware. I have my forked version working with our external auth system and I've put some example code a comment showing what I did on the plugin side. The PR does not implement login/adduser functionality which I leave to the external system. That means that running `npm login|adduser --registry http://0.0.0.0:4873` won't generate a token in the `.npmrc` but rather the user would need to get that and put it in themselves from an external system.
