### ISSUE TITLE
Act sensibly in the face of read-only storage.

### ISSUE THREAD

**Issue by akdor1154** [verdaccio/verdaccio#125]
I want to deploy multiple instances of Verdaccio configured with a shared NFS volume as storage. I will set one of those instances to have that storage mounted as writable, with the rest as read-only. I will use a load balancer in front of the instances to redirect GET requests to any of the read-only instances, and other ACTION requests to the writable instance. I know this isn't supported, but with a glance through the code, it should work reasonably already, and only a couple of changes that I can see would be needed for me to trust it completely.

Currently some operations (I have tested `publish`) will hang forever (send back 500s) on the client if storage is not writable. It would be great if these could fail instantly with an error code that causes `npm` to fail instead of retry.

I believe this is purely due to how the writing functions in `local-storage.js` work. On brief inspection, if these were to catch `EACCESS` failures and respond with something that will stop `npm` clients in their tracks, this would be enough to have this setup work properly (I just would rather have the read-only clients fail instantly so the load balancer can pick up that an error has occured).

Would a change like this be considered?

**Comment by jachstet-sea** [comment]
I'd personally start by researching what "will stop npm clients in their tracks" if a HTTP 500 (which is actually pretty clear) makes them keep on retrying. Since it's a server-based error (and not something that the client did wrong), you'd use a 5XX status code. And you use one that is permanent i.e. gives the npm client a reason not to retry. In the list of wikipedia at https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#5xx_Server_Error I don't see anything fitting better than a 500.

**Comment by akdor1154** [comment]
Yeah, verdaccio's behaviour would make perfect sense in the hypothetical scenario of a sensible and standards-compliant client. Unfortunately `npm` appears to be neither of those things..

**Comment by Nicholaiii** [comment]
I am assuming this is to limit write access to the registry?
In this case, a 403 is perfectly sensible.

**Comment by juanpicado** [comment]
I wonder whether this has been tested with `yarn` or the last `npm` persist with the same issue?
