### ISSUE TITLE
Incomplete Node.js build environment in v4 Docker container

### ISSUE THREAD

**Issue by Elberet** [verdaccio/verdaccio#1266]
I deploy Verdaccio on an internal docker host; to facilitate installing third-party plugins, e.g. _verdaccio-auth-gitlab_, I build custom images from Verdaccio's official docker image.

My Dockerfile looks something like this:

```
ARG VERSION
FROM verdaccio/verdaccio:${VERSION}
RUN yarn add verdaccio-auth-gitlab
```

For Verdaccio v3, this works nicely, but my experiments with Verdaccio v4-alpha - e.g. `docker build --build-arg VERSION=4.0.0-alpha.4 .` -  have, so far, triggered two distinct problems:

1. The v4 containers run, by default, as user *verdaccio*, but several source files are owned by *root*. _yarn_ fails when trying to unlink `/opt/verdaccio/node_modules/.yarn-integrity`, _npm_ fails when trying to write files inside `/opt/verdaccio/node_modules/@verdaccio/file-locking`. This can be worked around by adding `USER` instructions in the Dockerfile but is still somewhat annoying.

2. The v4 container no longer contains a full Node.js and Python build environment: `node-gyp` fails with `Error: Can't find Python executable "python"` while NPM or Yarn is trying to install the _iltorb_ module.

I fully realize that v4 is an alpha release, and that _verdaccio-auth-gitlab_ does not officially support v4 anyways, but having a stable and working build environment for easy plugin installation in the Docker image should IMO be an important feature of the final v4 release. 🤔

**Comment by juanpicado** [comment]
cc: @dlouzan

**Comment by dlouzan** [comment]
In v4, two of the biggest motivators are:

1. Avoid running things as root, since this is a bad thing (tm)
2. Support environments where this no-root policy is enforced by the runtime (e.g. Kubernetes OpenShift) and integrate it into the [Helm chart](https://github.com/helm/charts/tree/master/stable/verdaccio).

The way we foresaw is to make plugins use the docker builder pattern. You then have full freedom to use whichever image you want for building your plugin, as long as you then afterwards copy the artifacts in the final verdaccio image. You can take a look at the [verdaccio-gitlab Dockerfile](https://github.com/bufferoverflow/verdaccio-gitlab/blob/master/Dockerfile) for a sample of this usage.

Would this solve all your concerns with v4? I agree it would make sense to make this explicit in the documentation.

**Comment by Elberet** [comment]
Sure, since you've basically redesigned the approach to installing plugins, concerns about a build env inside the main verdaccio docker image aren't really valid anymore.

But yeah, the documentation on that is very bare, so far.
