### ISSUE TITLE
Custom logger format

### ISSUE THREAD

**Issue by alunny-stripe** [verdaccio/verdaccio#1286]
**Is your feature request related to a problem? Please describe.**
My company uses [splunk](https://www.splunk.com/) to manage log files. We typically log from services using [splunk's key-value](https://docs.splunk.com/Documentation/AddonBuilder/2.2.0/UserGuide/ExtractFields#Key_Value) format to make ad-hoc querying much easier.

**Describe the solution you'd like**
I'd like to write a logger plugin that defines a key-value log format, so instead of, eg:

`[2019-04-25 17:55:33.561486]  http <-- 200, user: null(127.0.0.1), req: 'GET /-/ping', bytes: 0/3`

we could log

`[2019-04-25 17:55:33.561486]  http_status=200 user=null user_ip=127.0.0.1 http_method=GET path="/-/ping"`

or something like that.

I'm not sure if this would be best as a special type of verdaccio plugin (a logger plugin) or if we could configure a Bunyan instance and pass it to verdaccio (either through yaml config or the node.js API).

**Describe alternatives you've considered**

**Additional context**
Thanks for working on Verdaccio! We've been really impressed with our early experimentation with it.

**Comment by juanpicado** [comment]
hi @alunny-stripe !

Actually, I'd love to change the whole `logger` which is the same one since `sinopia@1.4.0`. So I'm totally open a new design here but keeping the internal log API. eg:

```
self.logger.warn({ err: err, fileName: file }, 'error saving file @{fileName}: @{err.message}\n@{err.stack}');
```
I was thinking to use something different than `Bunyan` without Node.js native dependencies (I think Bunyan uses `dtrace-provider@0.8.7`)`. My alternative in my mind is:

https://github.com/pinojs/pino

So, to achieve this first we need to literally write it from scratch.

**Comment by mlucool** [comment]
I too prefer a jsonl style logger (bunyan, pino, etc) as it makes parsing downstream much, much easier

**Comment by juanpicado** [comment]
I'll close this one in favor of https://github.com/verdaccio/verdaccio/issues/1334  Let's follow up there.
