### ISSUE TITLE
Probably unused dependencies

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#1292]
**Describe the bug**
I did a check with `depcheck` and got the following result.
I did not find some reference of the listed dependencies in the code.

**To Reproduce**
1. `yarn global add depcheck`
2. `depcheck`

**Expected behavior**
There should be no unused or missing dependencies.

```
Unused dependencies
* global
* js-base64
* js-string-escape
* lockfile
* verdaccio-audit
* verdaccio-htpasswd

Unused devDependencies
* @commitlint/cli
* @commitlint/config-conventional
* @verdaccio/babel-preset
* @verdaccio/types
* eslint-config-prettier
* eslint-plugin-import
* flow-runtime
* husky
* verdaccio-auth-memory
* verdaccio-memory

Missing dependencies
* babel-eslint
* @babel/register
* get-stdin
* babel-polyfill
```

**Comment by juanpicado** [comment]
@DanielRuf many of those broken or missing links are because we load plugins dynamically. For instance, `verdaccio-audit`, `verdaccio-htpasswd` are quite funny discover, since are essential for the registry functionality. 

About devDependencies. 

```
* @commitlint/cli
* @commitlint/config-conventional
* @verdaccio/babel-preset
* @verdaccio/types
eslint-config-prettier
* eslint-plugin-import
* flow-runtime
* husky
* verdaccio-auth-memory
* verdaccio-memory
```
All of them are being used, not 100% about`flow-runtime`. And the Missing dependencies ... not sure what tha means. 

👍 To be removed `lockfile`, `global`, `js-base64`.

Good catch, I'll remove those are legacy when I removed UI from this repo.

**Comment by DanielRuf** [comment]
Right, I found many after some manual checks.
Not sure if we could iprove something in `depcheck` or could need another tool to do these checks.

I guess the missing dependencies are references but not found or installed.
Will have to check these.

**Comment by juanpicado** [comment]
Actually ... I did not see `babel-polyfill` and `get-stdin`. In the case of `babel-eslint` are `@babel/register` are inner dependencies.

**Comment by juanpicado** [comment]
`babel-polyfill` is not needed here `test/lib/helper/register.js` and `get-stdin` is completely missing.
