### ISSUE TITLE
Using s3 storage plugin with uplink doesn't work

### ISSUE THREAD

**Issue by Jbonavita** [verdaccio/verdaccio#1354]
We added the verdaccio-s3-storage plugin so we can have multiple servers using a single storage location. Everything works fine as long as the packages we're looking for are in our private repo. 
If the packages are in the uplink, in our case registry.npmjs.org, we get a bad request error. To verify that the issue is caused when a storage plugin is added, I removed the storage plugin and tried again and everything worked as expected.

Is there any way to accomplish what we're trying to do?

We're running Verdaccio 3.11.6

**Comment by DanielRuf** [comment]
Hi @Jbonavita,

please provide some details about the NodeJS version and the S3 plugin version so we can reproduce this. Can you provide a small reproducible test case as repository?

**Comment by Jbonavita** [comment]
s3-storage@0.2.0
node -v: v6.16.0

Sorry, I can't create a repository accessible off our network.

**Comment by DanielRuf** [comment]
Can you share the relevant config parts with us?

**Comment by Jbonavita** [comment]
I attached the config.
[config.txt](https://github.com/verdaccio/verdaccio/files/3297670/config.txt)

**Comment by Jbonavita** [comment]
What other info is needed?

**Comment by juanpicado** [comment]
> To verify that the issue is caused when a storage plugin is added, I removed the storage plugin and tried again and everything worked as expected.

If the error is in the plugin then I'd suggest asking the author directly https://github.com/Remitly/verdaccio-s3-storage 

> we get a bad request error.

Which error?

**Comment by Jbonavita** [comment]
I'm not really sure what the expected behavior/work flow is when there's a uplink used in combination with a storage plugin.

With no uplink, all reads/writes/deletes would go to the S3 bucket. This makes sense and works as expected.

However, if there is an uplink, what does a storage plugin mean? Shouldn't it defer to the uplink for storage thus not using a storage plugin?

I'm trying to learn how it's suppose to work so please excuse if me I'm asking a basic question.

**Comment by juanpicado** [comment]
@Jbonavita

>I'm not really sure what the expected behavior/work flow is when there's a uplink used in combination with a storage plugin.

Actually, nothing, both are completely independent pieces, storage plugins are just transparent for uplinks, technically, the uplink stream is piped with a writeable stream provided by the plugin through a core class. 

Since you haven't provided the error, we are blind I cannot emit any diagnostic. 

> However, if there is an uplink, what does a storage plugin mean? Shouldn't it defer to the uplink for storage thus not using a storage plugin?

Storage plugins are just an extension of methods see, https://github.com/verdaccio/flow-types/blob/master/index.d.ts#L363 . Storage plugins just do one single thing, write and read from a stream, that's all.

However,  we have an example https://github.com/verdaccio/docker-examples/tree/master/amazon-s3-docker-example using S3 plugin with **Localstack**, I think that would be useful to reproduce the error if you need to do a PoC.
