### ISSUE TITLE
User management

### ISSUE THREAD

**Issue by Bram-Zijp** [verdaccio/verdaccio#1431]
**Is your feature request related to a problem? Please describe.**
I would like to have an GUI in which administrators can manage users and their rights to specific teams/groups.

**Describe the solution you'd like**
Create a standard for groups/teams and a dashboard in which administrators can manage users and their access to specific groups/teams. Make it file based so that users can back it up and download it to update their code repositories. This enables to spin up a new cluster based off the config files in ones code repository when a recovery is required. One could even think of automating the updating of the code repositories on changes from the management GUI.

**Additional context**
This feature is in demand by enterprises. Add a payment requirement for this feature based on the ammount of users. For instance 1-50 users for free, 50-150 for 50 euro's a month and 150-250 for 100 euro's a month while incrementing costs by this basis. Big companies won't scam for such low prices and it will net more then your current donation model.

**Comment by juanpicado** [comment]
hi @Bram-Zijp 

> I would like to have an GUI in which administrators can manage users and their rights to specific teams/groups.

The feature is nice to have, but, this would be really hard to maintain since anyone can use a different auth plugin and this feature would be not practical for those users. Personally, I would not support this idea, I think if someone needs this feature, they can easily extend the UI, create some sort of middleware plugin and do it themselves.  As you exposed, "demand by enterprises", they have plenty of resources to invest in such things, as an example 😉 https://github.com/lyft/verdaccio and I haven't seen any of those corporations donating to Verdaccio by far. That's just one example, there are many big corporations doing exactly the same thing. 

> Add a payment requirement for this feature based on the ammount of users. For instance 1-50 users for free, 50-150 for 50 euro's a month and 150-250 for 100 euro's a month while incrementing costs by this basis. Big companies won't scam for such low prices and it will net more then your current donation model.

Mmmmm, I'm not sure what's the connection of this part with the request above. But in any case, the vision of this project is not create a business in logn term, rather than create a free and open alternative for those cannot afford `JFrog`, `npmjs`, `GemFury`, etc etc.

**Comment by Bram-Zijp** [comment]
I think disabling adduser and managing users via htpasswd solves this problem.
