### ISSUE TITLE
'npm adduser' returns error 405 IIS 7.  WebDAV module

### ISSUE THREAD

**Issue by IngMalva** [verdaccio/verdaccio#1449]
I setup Verdaccio on IIS 7.5. The web interface is up at the desired address.
When I try to execute `npm adduser --registry  http://my.registry.it/`, as requested in the UI, I get an `npm ERR!` saying 

> HTTP Error 405.0 - Method Not Allowed

It seems a configuration problem with the WebDAV module, but I tried to:

1. give the WebDAV module various permissions, including executing and scripting and added "all verbs"
2. manually generate a user entry in ./htpasswd. This step led me to login via UI, but not via CLI
3. give the user that runs Verdaccio Application Pool all permissions

Please, help me out :)

Screenshots below.

**Web UI:**
![image](https://user-images.githubusercontent.com/7755143/63576812-45958c00-c58d-11e9-8362-71bb71e8a403.png)

**The CLI error, put in htm file for convenience:**
![image](https://user-images.githubusercontent.com/7755143/63576896-78d81b00-c58d-11e9-8d36-028e88863e35.png)

**Comment by juanpicado** [comment]
hi @IngMalva unfortunately I do not have any environment which I can test WebDAV, I don't know whether any @verdaccio/collaborators might have some answer for you.

I'd recommend rather post in StackOverflow since the error seems not to be a bug related with Verdaccio, unless I'm wrong and is a legitimate bug could remains open.

**Comment by juanpicado** [comment]
Let's follow up here https://stackoverflow.com/questions/57653725/npm-adduser-returns-error-405-iis-7-webdav-module
