### ISSUE TITLE
Allow ".yml" config extension

### ISSUE THREAD

**Issue by gn-jgeerds** [verdaccio/verdaccio#1528]
**Describe the bug**
Verdaccio silently ignores a config named "/verdaccio/conf/config.**yml**" and create a default config under "/verdaccio/conf/config.**yaml**".

I'm not sure if this is enough to call it a bug. This is more an enhancement but could also be a security related issue. You can even ignore this report. I just thought it was worth a GitHub issue.

I accidentally used the wrong filename extension for the config and wondered why my changes are not working. Sure, this is absolutely my fault but I think this bug is easy to hit.

If someone wants an "almost" default config except for some scope restrictions or similar like that, this could be a security related issue if the user doesn't check if the configured restrictions work as expected.

**To Reproduce**
Follow the documentation, accidentally use the wrong config filename suffix and deploy verdaccio via Docker Swarm ;-) 

**Expected behavior**
There are several possible solutions and I'm not sure which is the best one. I think supporting both filename extensions would be great.

**Comment by juanpicado** [comment]
hi @gn-jgeerds , I understand your concern. The extension `yaml` has been used since Sinopia (before this fork), so it is kinda embedded already in the big base of users. Anyway, for the moment the documentation says clearly `yaml` and as far I can see there is a long [debate](https://stackoverflow.com/questions/21059124/is-it-yaml-or-yml) about it. 

For me is fine like it is, but I'm open to listen other thoughts.
