### ISSUE TITLE
Binary downloads are not cached

### ISSUE THREAD

**Issue by Hanterdro** [verdaccio/verdaccio#175]
Some packages like node-sass have an install script which have a binary download:

```
> node-sass@3.13.1 install /Users/xxx/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v3.13.1/darwin-x64-51_binding.node
Download complete  ⸩ ⠋ :
```

This binary download is not cached by verdaccio.

**Comment by Meeeeow** [comment]
This download is not handle by NPM and will not send to registry, so we can't cache it anyway.

They use "post-install script" to download this binary

**Comment by TheILPlace** [comment]
if this question is because of and installation of angular-cli, then there are 3 ways to resolve this:
1. npm install -g @angular/cli --no-optionals  
2. copy from another computer's npm-cache folder, the node-sass folder
3. read the documentation of node-sass , you can download the binary beforehand put it on your network and point there using environment variable
