### ISSUE TITLE
Verdaccio with async middleware

### ISSUE THREAD

**Issue by frimuchkov** [verdaccio/verdaccio#1912]
I've found out there is no way for using async middlewares due to freezing in body-parser after any await

```
 export default class VerdaccioAsync implements IPluginMiddleware<Config> {
    logger: Logger;

    constructor(_config: Config, options: PluginOptions<Config>) {
        this.logger = options.logger;
    }

    // eslint-disable-next-line @typescript-eslint/camelcase
    register_middlewares(app: Application): void {
        app.use(async (req, res, next) => {
            await new Promise(resolve => setTimeout(resolve, 100));
            return next();
        });
    }
}
```

It's a bug, not a feature request

https://github.com/expressjs/body-parser/issues/411

**Comment by frimuchkov** [comment]
This code in logger is the reason of this behaviour:
```
  req.on('data', function(chunk): void {
    bytesin += chunk.length;
  });
```

**Comment by frimuchkov** [comment]
Seems it's relates to https://github.com/verdaccio/monorepo/pull/371

**Comment by juanpicado** [comment]
Well, at this point I don't plan to change the logger, would be a breaking change and I consider master freeze for incoming features since I'm working actively on branch `5.x` and I have no time to maintain two development lines.

We plan breaking changes for plugins, feel free to check it out and maybe your concern might be cleared there.
https://github.com/verdaccio/verdaccio/milestone/22
