### ISSUE TITLE
CSRF for Verdaccio

### ISSUE THREAD

**Issue by royaldevbrat** [verdaccio/verdaccio#1937]
Did you implemented/considered CSRF in verdaccio?

**Comment by DanielRuf** [comment]
Do you mean CSRF tokens for the frontend part or checks in the backend?
We use JWT tokens for authentication (server / backend).

**Comment by royaldevbrat** [comment]
Do you mean CSRF tokens for the frontend part or checks in the backend?- Yes, But Daniel  I believe Cross Site Request Forgery is different from JWT.

**Comment by DanielRuf** [comment]
Yes frontend or backend?
I am aware of CSRF in general but I do not completely understand what you mean or where we need any CSRF tokens and to mitigate which risks.

Can you explain this in detail?
Or is this just a general idea / question (about CSRF protection)?

Or did you find a vulnerability? If so, please read our security pilicy.
https://github.com/verdaccio/verdaccio/blob/master/SECURITY.md

**Comment by royaldevbrat** [comment]
I am looking for implementation of below or similar requirement in Verdaccio which i got it from my cyber security advisor: 

- Components must verify that the REST service is protected from Cross-Site Request Forgery.
- Components must verify that the application or framework uses strong random anti-CSRF tokens or has another transaction protection mechanism.

**Comment by DanielRuf** [comment]
Afaik we use tokens and encrypted JWT to authenticate users.
No random token per request afaik, like it is used for forms in web frameworks to protect against CSRF.

The same applies to the npmjs. As a user / developer you have a token on your local computer (for npmjs it is in the `~/.npmrc` file).

See
<img width="233" alt="Bildschirmfoto 2020-09-10 um 17 55 11" src="https://user-images.githubusercontent.com/827205/92758249-cdb02480-f38e-11ea-8dd2-74c447f2b51d.png">

I guess the advisor does not know much about how a registry (like packagist for composer, npmjs for npm and yarn, verdaccio for npm and yarn, ...) works.


If a user things a token is stolenm, it can be revoked (same at npmjs).
The service itself can not check such a CSRF token because npm and yarn do not send such information with requests. So there is nothing that we could add or verify that is not in the default logic of npm and yarn.

So I think this does not apply to verdaccio and can not be implemented as this would not prevent thr abuse of stolen tokens from `~/.npmrc`.
What do you think @juanpicado?

**Comment by juanpicado** [comment]
>  I think this does not apply to verdaccio and can not be implemented as this would not prevent thr abuse of stolen tokens from ~/.npmrc.

I'm not sure whether @royaldevbrat refers to the web or the CLI itself. Anyway, the website is read-only, no transactions involved, the unique POST is the log in which returns a unique JWT token and by default expires really soon (7 days) by default.

> I think this does not apply to verdaccio and can not be implemented as this would not prevent thr abuse of stolen tokens from ~/.npmrc.

Same thoughts here, we cannot prevent anyone stole tokens at `~/.npmrc`.

**Comment by DanielRuf** [comment]
> the website is read-only, no transactions involved, the unique POST is the log in which returns a unique JWT token and by default expires really soon (7 days) by default.

Exactly. Currently I fail to see how the two points mentioned by the advisor apply to verdaccio.
Is this a requirement for you that you are allowed to use verdaccio in your company @royaldevbrat?
Was this the result of some audit or just some general advice?

**Comment by royaldevbrat** [comment]
> Is this a requirement for you that you are allowed to use verdaccio in your company @royaldevbrat?

@DanielRuf Yes
> Was this the result of some audit or just some general advice?

@DanielRuf These are coming from a audit tool as OWASP requirement list for web and client application.

> I'm not sure whether @royaldevbrat refers to the web or the CLI itself. 

@juanpicado  This is general requirement for client(Mostly Web) and server application. Tool does not considered Client as CLI

**Comment by DanielRuf** [comment]
> @DanielRuf These are coming from a audit tool as OWASP requirement list for web and client application.

OWASP ZAP and similar? Well, these are just regular checks and this one does not apply to verdaccio as @juanpicado explained. So this is some sort of false-positive / low risk that can be ignored as this is not applicable.

The web version / frontend is just for pulling / fetching packages. The CLI / server part for uploading. But technically we can not add any sort of CSRF checks there (which make not much sense) and can only use the token that the npm clients pass through (and not more things that you would like to provide like some sort of CSRF token).

See also:
https://docs.npmjs.com/about-authentication-tokens
https://verdaccio.org/docs/en/best#security 
https://verdaccio.org/docs/en/best#expiring-tokens

I think we can close this issue as wontfix as CSRF tokens make not much sense here.

**Comment by royaldevbrat** [comment]
I agreed. We can close this issue. @DanielRuf ans @juanpicado  Thanks for clarification. Good Luck.
