### ISSUE TITLE
Can I make a fully offline repository

### ISSUE THREAD

**Issue by Tixxxon** [verdaccio/verdaccio#1956]
Hi! Is it possible to cache all available versions of the package? I need a full local version of the npm repository as sometimes I don't have Internet access
THX

**Comment by juanpicado** [comment]
Verdaccio only downloads by demand. Not possible to download all versions unless you do it on your own.

**Comment by Tixxxon** [comment]
Thank you, sad :(

**Comment by juanpicado** [comment]
Just to give you context, any other proxy registry works in the same way, either Nexus or relatives.

**Comment by Tixxxon** [comment]
The problem is that in package.json package records are added for all versions. And if, for example, you use the "vue create project" command, Vue downloads the latest available version of webpack, and it may not always be in the cache, and there is no Internet access either. and it is not clear what to do

**Comment by Ebsan** [comment]
Yeah, we also need a similar solution and it would differentiate Verdaccio from other proxy solutions if we could toggle this on/off.

**Comment by juanpicado** [comment]
@Ebsan what exactly is your desired scenario? Just curiosity to understand.

**Comment by Ebsan** [comment]
Thanks for the quick reply. 

We'd like to set up a full mirror of npmjs since we're working in a fully offline environment. We'd like to set up a mirroring solution to mirror npmjs.org and then bring a copy of that into our offline network. With the proxy solutions we'd have to get a list of all the npm packages on npmjs, update this list with package updates, and npm install each one to cache those tarballs. It would be nice if Verdaccio could do that all on it's own (cache all tarballs, and bring in any updated versions) without having to do the npm install step.

**Comment by juanpicado** [comment]
> We'd like to set up a full mirror of npmjs since we're working in a fully offline environment. We'd like to set up a mirroring solution to mirror npmjs.org and then bring a copy of that into our offline network

Seems like a lot, doesn't it?  In 2012 was 16GB, nowadays is around 500TB as far I remember. 

https://twitter.com/npmjs/status/239979010782818304

You would need more than Verdaccio for that.

> It would be nice if Verdaccio could do that all on its own (cache all tarballs, and bring in any updated versions) without having to do the npm install step.

Remember one thing, **Verdaccio works by demand**, so the one which actually fetches packages is the package manager, not the registry, the registry does not think on its own and, furthermore, the public registry mutate almost every millisecond, so, that 500 TB copy would become useless the next day because you will need to update your dependencies eventually, does worth it?

https://stackoverflow.com/questions/6383894/npm-registry-alternative-to-http-registry-npmjs-org-npm

What you need is "doable", if you have enough resources, but nowadays is almost impossible.

**Comment by josh-hemphill** [comment]
Is it possible to manually add public packages from `node_modules` directories? Such that it could be running offline but specific versions of specific packages that have been audited to be allowed in the environment could be added so build tools would work like normal and the dependency tree could be kept out of version control?
