### ISSUE TITLE
url_prefix without hostname doesn't work

### ISSUE THREAD

**Issue by jpap** [verdaccio/verdaccio#207]
According to the [documentation](https://github.com/verdaccio/verdaccio/blob/master/SERVER.md#run-behind-reverse-proxy-with-different-domain-and-port),

> If you do not know the protocol and host, you can define only subpath as url_prefix. Full URL will be constructed from the request.
>
> `url_prefix: '/your-path'`

But when I try to do this, as follows, the server returns JSON with the `tarball` field having blank protocol and server name, which then makes `npm` choke.
  ```
  url_prefix: '/'
  ```

When I set the `url_prefix` to be a proper protocol and hostname (e.g. `http://my.domain.local/`) then everything works as expected.

I'm running Verdaccio behind a reverse-proxy.

**Comment by juanpicado** [comment]
Perhaps @Meeeeow has an idea.

**Comment by Meeeeow** [comment]
Can't reproduce that on verdaccio/2.1.7

Try run:
```
verdaccio --version
```

**Comment by Meeeeow** [comment]
@jpap Would you like provide more info to help us make verdaccio better?

**Comment by Meeeeow** [comment]
Sorry for the delay and the wrong judgment.

I can confirm verdaccio server will run with `url_prefix: '/'`, but this will never work on npm side.
The author of this issue meet an error called *"Only absolute URLs are supported"*, because the tarball address in verdaccio's response is relative path, like `/pkg/-/pkg-1.0.1.tar.gz`

@juanpicado Maybe we should't allow user set url_prefix to `/`? I will update the document later.

It's possible to detect remote address by host (Just don't set `url_prefix`), but almost all reverse proxy software will not send real request domain and port to backend, so the tarball address will be `http://127.0.0.1:4873/foobar.tar.gz`, then everything is broken :(

@jpap You should configure your nginx server like this (It works, tested.):
```nginx
location / {
    proxy_pass http://127.0.0.1:4873/;
    proxy_set_header Host            $host:$server_port;
    proxy_set_header X-Forwarded-For $remote_addr;
}
```

and

**Remove `url_prefix` from configure**

**Comment by Meeeeow** [comment]
@juanpicado PR #214

**Comment by jpap** [comment]
@Meeeeow, thanks for looking into this in more detail!

I'm behind the [Kubernetes nginx ingress](https://github.com/nginxinc/kubernetes-ingress).  By default, it includes the headers (partial config listed) below.  If you're honoring `X-Forwarded-For`, shouldn't this configuration have already worked?

```
# Obtain best http host
map $http_host $best_http_host {
    default          $http_host;
    ''               $host;
}

proxy_set_header Host                   $best_http_host;

proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Host       $best_http_host;
proxy_set_header X-Forwarded-Port       $pass_port;
proxy_set_header X-Forwarded-Proto      $pass_access_scheme;
proxy_set_header X-Original-URI         $request_uri;
proxy_set_header X-Scheme               $pass_access_scheme;
```

Please LMK if there's anything else I can provide -- header dumps, verbose logs, etc.w

**Comment by Meeeeow** [comment]
Your config should work after remove `url_prefix` field from verdaccio config (don't forget restart), X-Forwarded-For just send real client IP to verdaccio server.

Did this work for you? If it still not work after remove `url_prefix`, please reply and tell me how to i reproduce it :)
