### ISSUE TITLE
Serve from cache for specific version

### ISSUE THREAD

**Issue by AlexShemeshWix** [verdaccio/verdaccio#208]
Hi
I have verdaccio 2.1.1 running on Ubuntu 14.04.
Node version 7.0.0

I would like to propose a feature:
Server should serve cached version of package if specific version requested, without sync with upstream registry.
Right now server will sync package.json with upstream registry before returning package tar ball. If upstream registry is down, it will produce timeouts and it will make installation process longer.
Upstream registry may also contain bloated package.json so sync will increase size of local version of package.json. To the point that it will affect CPU time of application.

If user requests specific version, and this version present in local cache, server should return local version without connecting to upstream registry.

**Comment by juanpicado** [comment]
Do you have any idea how the configuration would looks like?

**Comment by AlexShemeshWix** [comment]
Hi

```
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    timeout: 5s
    specver: <local/default>

```

local - in case of specific version serve from local if present, no sync with upstream
default - sync with upstream before serving version.

**Comment by juanpicado** [comment]
> Server should serve cached version of package if specific version requested, without sync with upstream registry.

Actually, you can do that without any change, **just do not define any proxy** and follow this http://www.verdaccio.org/docs/en/packages.html#blocking-proxying-a-set-of-specific-packages

> If user requests specific version, and this version present in local cache, server should return local version without connecting to upstream registry.

I'm afraid we cannot do it, the reason is how the node package managers work. Check the following log.

```
➜ npm install jquery@beta -d   
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v9.4.0
npm http fetch GET 200 http://localhost:4873/jquery 83ms
npm http fetch GET 200 http://localhost:4873/jquery/-/jquery-3.3.1.tgz 286ms
npm info lifecycle jquery@3.0.0~preuninstall: jquery@3.0.0
npm info lifecycle jquery@3.0.0~uninstall: jquery@3.0.0
npm info lifecycle jquery@3.0.0~postuninstall: jquery@3.0.0
npm info lifecycle jquery@3.3.1~preinstall: jquery@3.3.1
npm info linkStuff jquery@3.3.1
npm info lifecycle jquery@3.3.1~install: jquery@3.3.1
npm info lifecycle jquery@3.3.1~postinstall: jquery@3.3.1
npm info lifecycle undefined~preshrinkwrap: undefined
npm info lifecycle undefined~shrinkwrap: undefined
npm info lifecycle undefined~postshrinkwrap: undefined
```

You might appreciate there are two endpoint calls. First one request all metadata for such package, `npm/yarn` **does not receive any information aside from the package name**. Then, if the first call is successful `npm` receive and **resolve the version locally with such metadata whether the version is in the registry or not and then request the tarball**.  As last step verdaccio serves the file whether is local otherwise lookup the file on uplinks.

Try to request an unexisting package. There is only one endpoint request. 

```
➜ npm install jquery@45555 -d  
npm info it worked if it ends with ok
npm info using npm@5.6.0
npm info using node@v9.4.0
npm http fetch GET 200 http://localhost:4873/jquery 412ms
npm http fetch GET 200 http://localhost:4873/jquery 51ms
npm ERR! code ETARGET
npm ERR! notarget No matching version found for jquery@45555
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

We cannot optimize as you suggested due node clients limitations.
