### ISSUE TITLE
Logger deprecation warning - documentation update needed

### ISSUE THREAD

**Issue by jeffrson** [verdaccio/verdaccio#2300]
**Describe the bug**

Without a valid logger configuration verdaccio always outputs a deprecation warning about "multiple logger configuration".

This is apparently due to
https://github.com/verdaccio/verdaccio/blob/master/packages/logger/src/logger.ts#L101
which wraps DEFAULT_LOGGER_CONF in an array if there's no logger configuration in current config.

Furthermore, https://verdaccio.org/docs/en/configuration as well as the migration guide at https://verdaccio.org/blog/2021/04/14/verdaccio-5-migration-guide (the latter being worse) both show the old way of defining log configuration. Instead it should be IMO

```yaml
logs:
  type: stdout
  format: pretty
  level: http
```
or
```yaml
logs: { type: stdout, format: pretty, level: http }
```

Kind of confusing...

(verdaccio 5.1.1)

Edit: btw, pino does not seem to support a log level called "http" - so this should probably be "info"?!

**Comment by juanpicado** [comment]
> pino does not seem to support a log level called "http"
It does not, it is an idea that was added in `sinopia` long time ago, but pino allows add customs levels

https://getpino.io/#/docs/api?id=customlevels-object

@jeffrson thanks for reporting the mismatch,  feel free to update documentation, all help is very welcome.

**Comment by haquezameer** [comment]
@juanpicado Would like to pick this up. From what I understood, the deprecation warning comes because multiple loggers are not allowed in `verdaccio - 5` but if users don't define any logger config then by default verdaccio is assuming `LoggerConfig = [DEFAULT_LOGGER_CONF]` due to which [isLegacyConf](https://github.com/verdaccio/verdaccio/blob/master/packages/logger/src/logger.ts#L104) check passes and the deprecation message is shown - but should not be shown because user did not actually configure multiple loggers.

Changing the default logger to `LoggerConfigItem = DEFAULT_LOGGER_CONF` should fix this?

**Comment by juanpicado** [comment]
Yes, you are right, that should fix it :) please go ahead.

**Comment by haquezameer** [comment]
@juanpicado created a PR with the above discussed changes. Please review and let me know if any changes required. Thanks 😄
