### ISSUE TITLE
Verdaccio doesn't update from company uplink registry

### ISSUE THREAD

**Issue by will-l-h** [verdaccio/verdaccio#268]
My company has a JFrog registry for private packages and I believe I set up verdaccio correctly to point to it as an uplink.  The issue is that it seems that verdaccio won't pull down updates to the package set for the uplink: foo-ui-theme. If I delete it from the storage folder, verdaccio will get everything, including the latest. 

This may be due to all versions being alpha (e.g. 1.0.0-alpha.1, 1.0.0-alpha.18

```uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  foo:
    url: http://artifactory.foo.com/artifactory/api/npm/npm-foo

packages:  
  'foo-ui-theme':
    access: $all
    proxy: foo
  
  '@*/*':
    # scoped packages
    access: $all
    publish: $authenticated
    proxy: npmjs
```
#### Steps to reproduce:

If the latest that verdaccio has is 1.0.0-alpha-13 from the first time it pulled down from the company registry but now the company registry has alpha-18 and I try npm i foo-ui-theme@1.0.0-alpha.18, it fails:

``` warn --- http address - http://localhost:4873/ - verdaccio/2.3.1
 info <-- 127.0.0.1 requested 'GET /foo-ui-theme'
 info --> making request: 'GET http://artifactory.foo.com/artifactory/api/npm/npm-foo/foo-ui-theme'
 http --> 406, req: 'GET http://artifactory.foo.com/artifactory/api/npm/npm-foo/foo-ui-theme' (streaming)
 http --> 406, req: 'GET http://artifactory.foo.com/artifactory/api/npm/npm-foo/foo-ui-theme', bytes: 0/79
 debug-=- updating package info
 http <-- 200, user: bob(127.0.0.1), req: 'GET /foo-ui-theme', bytes: 0/1159
```

####  App Version:	
2.3.1 running on Windows

**Comment by juanpicado** [comment]
I can confirm the bug. Let's see whether I can figure out the reason

**Comment by juanpicado** [comment]
The issue is when `etag` is present in the `package.json` within the local storage, in other words, since the very beginning a dependency is created we set a `etag` for cache purposes.

In my example I called the uplink `jfrog` and my dependency is for testing purpose

```
  "name": "@jota/npm-fix-issue-268",
  "version": "1.0.0-alpha-16",
````

```
"_uplinks": {
		"jfrog": {
			"etag": "3063f3739502c329be06a9a8035b3a7bbf7e5001",
			"fetched": 1501184832009
		}
	},
`````

The second time we request a new dependency version eg: `1.0.0-alpha-17`, in our code we check if the etag is available, which is the case of 100% of the cases after the first dependency has been cached, then, we set this header to the request `Accept: 'application/octet-stream'`.

```
if (_.isNil(options.etag) === false) {
      headers['If-None-Match'] = options.etag;
      headers['Accept'] = 'application/octet-stream';
    }
```
```
Accept: application/octet-stream
If-None-Match: 641995274d25059dbcb0de1ec5016cd01be6bdf4
Connection: keep-alive
Content-Type: application/xml
Origin: chrome-extension: //rest-console-id
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36
`````
And here it comes the issue, `Jfrog Artifactory` doesn't like this and fails returning `http 406`
```
Request Url: http://localhost:8081/artifactory/api/npm/npm/@jota%2Fnpm-fix-issue-268
Request Method: GET
Status Code: 406
Params: {}
````
To fix the issue enough removing 

```
headers['Accept'] = 'application/octet-stream';
```
As far I tested I haven't found any issue with `npmjs` registries to removing the header `Accept: application/octet-stream` . What do you think @Meeeeow ?

**Comment by will-l-h** [comment]
Thanks for sorting this so quickly! 

If my uplink config looks correct, maybe I"ll submit a PR to expand that wiki since it wasn't immediately clear to me what I need to do under the packages section. I somehow got the impression that verdaccio would automatically fall back to other uplink if a package couldn't be found on the first (npmjs).

**Comment by juanpicado** [comment]
@will-l-h 
>  I somehow got the impression that verdaccio would automatically fall back to other uplink if a package couldn't be found on the first (npmjs).

I have to comment this, `verdaccio` won't fall back to another `uplink` if fails with the assigned one. For instance. if it tries to resolve `foo-bar@1.0.0` , the storage will try to match the first package that fulfill the pattern, eg:

```
packages:
  '**':
    access: $all
    proxy: npmjs
  'foo-*':
    access: $all
    proxy: yarn
```
If we analyze the uplink selected in the example above `verdaccio` will try to resolves through `npmjs` as is expected, because is the **first match**, if it fails won't try on `yarn`.

Let's switch the order.

```
packages:
  'foo-*':
    access: $all
    proxy: yarn
  '**':
    access: $all
    proxy: npmjs
```
 In the following case, `foo-bar` will be resolved via `yarn` uplink.

So two important things here:

* `verdaccio` always resolves with the first package match.  So, **the order of the packages is important**.
* There is no fallback to another `uplink` if the designated `proxy/uplink` fails.

**Comment by juanpicado** [comment]
btw @will-l-h I'll be supper happy to see a PR  🎉

**Comment by juanpicado** [comment]
The way how we fixed the issue is incorrect. After a bit of research I've saw the following. See https://github.com/yarnpkg/yarn/issues/3136#issuecomment-294192301 and https://github.com/yarnpkg/yarn/pull/3153

So, instead remove completely the `Accept` header as we did

```js
if (_.isNil(options.etag) === false) {
      headers['If-None-Match'] = options.etag;
    }
``` 

we must

```js
if (_.isNil(options.etag) === false) {
      headers['If-None-Match'] = options.etag;
      headers['Accept'] = 'application/vnd.npm.install-v1+json; q=1.0, application/json; q=0.8, */*';
}
```
According https://github.com/npm/npm-registry-client/#requests 

It seems `JFrog` and `Nexus` [see](https://issues.sonatype.org/browse/NEXUS-12821) still does not support `application/vnd.npm.install-v1+json;`  if we set the `Accept` header we must include  `application/json`.

**Comment by juanpicado** [comment]
Another valid solution to override default headers for each uplink would be:
```yalm
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
    headers:
      Accept: "application/vnd.npm.install-v1+json; q=1.0"
  artficatory:
    url: https://mycompany.com/npm
    headers:
      Accept: "application/json"
```
