### ISSUE TITLE
Separate storage for published and proxy packages

### ISSUE THREAD

**Issue by 0rvar** [verdaccio/verdaccio#364]
I would like to be able to delete the cache every now and then to stop caching old package versions.
It would be nice to be able to specify a separate storage directories for proxy packages and published packages.

**Comment by juanpicado** [comment]
For clean cache, please check this one https://github.com/verdaccio/verdaccio/issues/343 (and vote 👍 ) and to separate storages I'd recommend use the `storage` property in packages https://github.com/verdaccio/verdaccio/blob/master/wiki/packages.md#configuration

**Comment by gengshenghong** [comment]
I want/like this feature too! It is ok to just put them in separate folder in my opinion, so that I can remove it with "rm -rf", and if I need backup, I can do anything like "cp && tar".

Not clear about the "storage" configuration usage, but it seems not the same purpose? It is to set package directories filter by package name? What I may want will be:
1. two folders
storage/cached
storage/local
2. all packages downloaded from uplink will go into "cached" folder
3. all packages published using "npm publish" will go into "local". It may override package in "cached"/uplink. When "npm install", it will first search package in "local" and then "cached", and then download from uplink  if needed.
In this way, I can simply "rm -rf storage/cached" anytime safely (if I do not want to make the storage too large). I can backup "storage/local".
4. The best I may want is that I can even disable the "cache" feature (this was mentioned in sinopia issues several times), in this way, it will just download from uplink everytime, and only used to host private packages I published.

**Comment by gengshenghong** [comment]
#131 Seems to be the (4) item I mentioned, that will be ok for my usage to disable cache! (but it will be still helpful if the storage are separate as I can see it still leaves the "package.json" file for un-cached packages).
