### ISSUE TITLE
Remove a published package

### ISSUE THREAD

**Issue by ASHV95** [verdaccio/verdaccio#365]
#### My reason:
Hello how can we remove a published package on my local npm repo?

#### Additional information:

	
 - `$ set DEBUG=express:* verdaccio` enable extreme verdaccio debug mode
 - `$ npm --verbose` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Windows, OS X/macOS, or Linux?:
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
 
 - Container:
   - I use local environment
   - I develop / deploy using Docker.
   - I deploy to a PaaS.

**Comment by Meeeeow** [comment]
npm unpublish --force yourPackage

**Comment by ORESoftware** [comment]
How to remove all packages from verdaccio?

**Comment by juanpicado** [comment]
Unique option, manually. There is no npm command for such thing.

**Comment by juanpicado** [comment]
Yes, stop server and remove the content from https://verdaccio.org/docs/en/cli#default-storage-location and restart.

**Comment by ORESoftware** [comment]
`~/.local/verdaccio/config.yaml` is an empty file on my Ubuntu machine. 

` $XDG_DATA_HOME` environment variable is empty.

 `$HOME/.local/share` has a lot of folders in there that do not relate to npm packages / verdaccio.

So which folder can I remove? Maybe the above is true because I am using verdaccio as a Docker container.

**Comment by juanpicado** [comment]
Ah, Docker, in that case locations are different, see https://github.com/verdaccio/verdaccio/blob/master/conf/docker.yaml#L14
