### ISSUE TITLE
Project / Fork Status

### ISSUE THREAD

**Issue by silkentrance** [verdaccio/verdaccio#38]
Since you want to publish this on npm and since the original maintainers seem to have abandoned the project, will this become a real fork, i.e. renamed binary and stuff?

**Comment by trentearl** [comment]
This was the goal, but there are some other "competing" forks.

You can see the discussion here: https://github.com/rlidwka/sinopia/issues/376

I'm open to advice on how to proceed

**Comment by silkentrance** [comment]
I'd say just go for it. The other forks aren't too active and the proposals made by the guy associated with IBM, if I remember correctly, have not yet made their way into the original code base.

**Comment by sullyme** [comment]
So this is the real Sinopia successor? Ho can I install it? From github link?

**Comment by trentearl** [comment]
@sullyme yes, you can isntall it from github right now, im working on getting something on npm. node 6 seems to have caused some problems

**Comment by qballer** [comment]
@trentearl  I am going to chose this project if it works as expected. I think the community needs to lean somewhere.

**Comment by juanpicado** [comment]
@trentearl I wonder what is the path this project gonna have, because, now I'm trying to figure out which fork I should use at work. As far I've seen (aside of bugfixes) in both fork, no big changes since last commit on sinopia original. I'm asking because you mention "how to proceed" and that scares me, how can I suggest something that probably tomorrow might ends up as the original? . I agreed with @silkentrance  go for it. Waiting for the npm package. 👍

**Comment by trentearl** [comment]
@juanpicado  Originally tests were failing on older versions of node and node 6. I now have the verdaccio working with node 6 but the older versions of node still fail. I would like to get these older versions working before it is published to npm.

I asked how to proceed because when I originally forked the project there were a few people who expressed they would like to be co-maintainers and they haven't spoken up since then.

I'm hoping to have time to get all tests passing this weekend.

**Comment by mrkongo** [comment]
Go verdaccio go!

**Comment by trentearl** [comment]
0.10 pass on travis but not locally on OSX. I think this is just because the tests are running by starting the server in a new process. I am trying to get the server in test to start in the same process.

**Comment by jsumners** [comment]
Why worry about 0.10 and 0.12? 0.10 will no longer be supported *at all* on 2016-10-01, and 0.12 will be the same on 2016-12-31. It doesn't make any sense to retain support for them going forward. If someone needs a repo for them then they can just use Sinopia, as it will be just as supported.

Deprecate support for them in Veradaccio and move on.

**Comment by trentearl** [comment]
@jsumners  Thanks I didnt realize it was imminent. I should have a version published in the next few days

**Comment by juanpicado** [comment]
I guess the same for iojs, still present in the .travis conf file.

**Comment by trentearl** [comment]
I have prepared the release for 1.0.0.

Unfortunately user lonelyclick has published verdaccio without informing anyone. This prevents me from publishing

I have emailed the user asking what there intentions are and if I can be collaborator.

**Comment by jsumners** [comment]
@lonelyclick that's seriously not cool.

**Comment by aeweidne** [comment]
@lonelyclick what gives, brah.

**Comment by lonelyclick** [comment]
I am so sorry, but when unpublish, I found this http://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy， what should i do ?

**Comment by jsumners** [comment]
Transfer ownership by adding @trentearl and removing yourself I suppose -- https://docs.npmjs.com/cli/owner

**Comment by lonelyclick** [comment]
```
→ npm owner ls
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.0
npm info attempt registry request try #1 at 12:49:20 PM
npm http request GET https://registry.npmjs.org/verdaccio
npm http 200 https://registry.npmjs.org/verdaccio
lonelyclick <670891929@qq.com>
trentearl <trent@trentearl.com>
npm info ok
```

done

**Comment by SEAPUNK** [comment]
Because the currently published version is 1.4.0, I'm assuming the maintainers will have to bump the version to a higher version (2.0.0?), and _then_ publish that.

On a side note, I wonder if it will be okay with @lonelyclick, unless he's a trusted maintainer, to maintain ownership alongside @trentearl on the npm package, as it will give lonelyclick publishing/deprecation/unpublishing/etc capabilities, potentially (intentionally or unintentionally) wreaking havoc on the published package.

**Comment by trentearl** [comment]
@lonelyclick  thank you so much!

Can you remove yourself? If you want to be collaborator, I would be happy to allow that after your contributions bring some trust to the project.

However this is not the correct way for you to have permission to the npm package.


@SEAPUNK I agree I have deprecate the 1.4.0 release and published the 2.0.0 release

**Comment by lonelyclick** [comment]
```
→ npm owner ls
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.3.0
npm info attempt registry request try #1 at 2:25:07 PM
npm http request GET https://registry.npmjs.org/verdaccio
npm http 200 https://registry.npmjs.org/verdaccio
trentearl <trent@trentearl.com>
npm info ok
```

@trentearl done

**Comment by SEAPUNK** [comment]
@lonelyclick Thank you!

**Comment by trentearl** [comment]
@lonelyclick  thanks!

**Comment by DanielSundberg** [comment]
Closed? Where is the future roadmap supposed to be discussed?

**Comment by juanpicado** [comment]
@DanielSundberg sorry for a super late reply. But in case of someone is interested on Roadmaps. We have one for the next release.

https://github.com/verdaccio/verdaccio/pull/376
