### ISSUE TITLE
Make documentation more accesible to audience

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#386]
#### My reason:

We want to move documentation to the main website. We want the documentation is better indexed and accessible for the audience.

Reference https://github.com/verdaccio/verdaccio.github.io/issues/2

The documentation must remain in markdown format but will be moved and generated to Github pages repository and public through `www.verdaccio.org`

**Comment by sarathkcm** [comment]
Hi,
Currently, documentation links provided in both the Readme file and the website redirects here: [https://github.com/verdaccio/verdaccio/blob/master/wiki/README.md](https://github.com/verdaccio/verdaccio/blob/master/wiki/README.md) which redirects here, [https://github.com/verdaccio/verdaccio/tree/master/doc](https://github.com/verdaccio/verdaccio/tree/master/doc) which says Page not found. Is it not available because of the ongoing work on documentation?

**Comment by juanpicado** [comment]
Yeah, I'm aware of that, the master branch is intended, I do not want to change after the merge. The doc folder is my fault :) it should be plural, thanks for notice it @sarathkcm

**Comment by juanpicado** [comment]
Documentation Beta Website
http://www.verdaccio.org/verdaccio/
