### ISSUE TITLE
Systemd ExecStart path different for me

### ISSUE THREAD

**Issue by metaa** [verdaccio/verdaccio#396]
I just activated the systemd service on my machine, but I noticed that the `ExecStart` path was different for me.

This is what the file deploys with: https://github.com/verdaccio/verdaccio/blob/6a8077a88389588e70429e95e18dce578d41ce8d/systemd/verdaccio.service#L8 ... but for me the correct path is `/usr/local/lib/node_modules/verdaccio/bin/verdaccio` (which gets linked to from `/usr/local/bin/verdaccio` aswell).

I just upgraded from v2.2.6, but I don't think that's the reason.

Could we try to make it somehow dynamic here, as in, detecting the right path and setting that in the systemd file or resolving that dynamically in it?

**Comment by Meeeeow** [comment]
```ini
ExecStart=/usr/bin/env verdaccio
SyslogIdentifier=verdaccio
```

@juanpicado We can use `/usr/bin/env` as a bridge to start the executable without specify absolute path of npm global modules path

**Comment by metaa** [comment]
@Meeeeow ohhhh, right, why didn't I think of that?

**Comment by vineetmadan** [comment]
I have the updated ExecStart path but still the service won't start for me. Here are the logs (from Puppet):

Debug: Exec[npm_install_verdaccio](provider=posix): Executing '/usr/bin/npm install verdaccio@latest '
Debug: Executing with uid=verdaccio: '/usr/bin/npm install verdaccio@latest '
Notice: /Stage[main]/Verdaccio/Nodejs::Npm[verdaccio]/Exec[npm_install_verdaccio]/returns: executed successfully
Debug: /Stage[main]/Verdaccio/Nodejs::Npm[verdaccio]/Exec[npm_install_verdaccio]: The container Nodejs::Npm[verdaccio] will propagate my refresh event
Debug: Nodejs::Npm[verdaccio]: The container Class[Verdaccio] will propagate my refresh event
Info: Nodejs::Npm[verdaccio]: Scheduling refresh of Service[verdaccio]
Debug: Executing: '/bin/systemctl is-active verdaccio'
Debug: Executing: '/bin/systemctl is-enabled verdaccio'
Debug: Executing: '/bin/systemctl unmask verdaccio'
Debug: Executing: '/bin/systemctl start verdaccio'
Debug: Running journalctl command to get logs for systemd start failure: journalctl -n 50 --since '5 minutes ago' -u verdaccio --no-pager
Debug: Executing: 'journalctl -n 50 --since '5 minutes ago' -u verdaccio --no-pager'
Error: Systemd start for verdaccio failed!
journalctl log for verdaccio:
-- Logs begin at Thu 2018-06-07 16:30:39 BST, end at Fri 2018-06-08 09:49:20 BST. --
Jun 08 09:49:20 app001v systemd[1]: Starting LSB: Verdaccio NPM Proxy/Cache Server...
Jun 08 09:49:20 app001v systemd[1]: verdaccio.service: control process exited, code=exited status=203
Jun 08 09:49:20 app001v systemd[1]: Failed to start LSB: Verdaccio NPM Proxy/Cache Server.
Jun 08 09:49:20 app001v systemd[1]: Unit verdaccio.service entered failed state.
Jun 08 09:49:20 app001v systemd[1]: verdaccio.service failed.

Error: /Stage[main]/Verdaccio/Service[verdaccio]/ensure: change from 'stopped' to 'running' failed: Systemd start for verdaccio failed!
journalctl log for verdaccio:
-- Logs begin at Thu 2018-06-07 16:30:39 BST, end at Fri 2018-06-08 09:49:20 BST. --
Jun 08 09:49:20 app001v systemd[1]: Starting LSB: Verdaccio NPM Proxy/Cache Server...
Jun 08 09:49:20 app001v systemd[1]: verdaccio.service: control process exited, code=exited status=203
Jun 08 09:49:20 app001v systemd[1]: Failed to start LSB: Verdaccio NPM Proxy/Cache Server.
Jun 08 09:49:20 app001v systemd[1]: Unit verdaccio.service entered failed state.
Jun 08 09:49:20 app001v systemd[1]: verdaccio.service failed.

Debug: Executing: '/bin/systemctl is-active verdaccio'
Debug: /Stage[main]/Verdaccio/Service[verdaccio]: Skipping restart; service is not running
----------------------------------------------------------------------------------------------------------------

Node version : v8.11.2
Npm version: v5.6.0
OS: Centos 7.4
