### ISSUE TITLE
Add support for README in AsciiDoc

### ISSUE THREAD

**Issue by jirutka** [verdaccio/verdaccio#464]
We have all documentation, including project READMEs, written in AsciiDoc format. Verdaccio does not support AsciiDoc and tries to render package READMEs as Markdown, which results in wrongly formatted “package detail”.

Suggestion: Use [asciidoctor.js](https://github.com/asciidoctor/asciidoctor.js) to render files with file extension `.adoc` and `.asciidoc`.

**Comment by juanpicado** [comment]
@jirutka `verdaccio` does not host README files, it read it from metadata and store it on package.json in the storage. I wonder how in the middle of this process we can do what you suggest.

https://github.com/verdaccio/verdaccio/blob/master/src/lib/local-storage.js#L155

**Comment by jirutka** [comment]
Where does it get the readme from? I thought that it reads it from the uploaded tarball, finds and reads file `/readme\.\w+/i` or something like that, doesn’t it?

**Comment by ayusharma** [comment]
I took a deep dive into this issue yesterday. It is hard to differentiate between *markdown* and *asciidoc* because NPM Client is making the request with **readme** key.  

For more information https://github.com/npm/www/issues/42

@juanpicado @jirutka  I am not sure that we should also implement or not because the request coming from NPM client does not have anything related to the type of readme. 

If we get the type of readme then it is very straightforward.

**Comment by jirutka** [comment]
@ayusharma Maybe you can detect it based on the content. Quick&dirty detection – if the file contains `^=+ \w` before (optional) `^#+ \w`, then it’s AsciiDoc, otherwise it’s Markdown.

**Comment by ayusharma** [comment]
@jirutka Thanks for your suggestion. I like the approach. I am waiting for the @juanpicado 's review on this.

**Comment by juanpicado** [comment]
It worth to experiment @ayusharma

**Comment by ayusharma** [comment]
I'll give a try :)
