### ISSUE TITLE
Migrate to CircleCI 2.0

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#612]
#### My reason:

https://circleci.com/blog/sunsetting-1-0/

#### Additional information:

I'll explain step by step what we are doing in a nutshell on `circleci.ylm`

* YARN_VERSION: 1.6.0
* verdacciobot user will perform all task 
* Testing with node 6, 8, 9 and 10
* Default node should be 9
* `yarn run pre:ci` first step before running anything else
* `- yarn run test:e2e` should be run once using default Node 
* Publish docusaurus after (master branch) is being successful (right now it publish even from branches and that is wrong)
* Deployment: This is really important
  * After a new tag is being detected we should deploy on `npmjs` `/(v)?[0-9]+(\.[0-9]+)*/`
  * `l10n_master` master branch should be ignored for builds (used by crowdin and it is nog being ignored currently). 
  * `gh-pages` is being used by docusaurus and also should be ignored. 

## Upgrade

* We should keep the same configuration
* Fix what is not working properly
* Deployment is essential
* Wish list:
  * Use of artifacts ( to measure the size of the tarball in each PR)
* Any another improvement that improves the workflow and maintainability 

## Testing

 * We should test in a separated repository (we cannot publish it accidentally on npmjs)

**Comment by pgrzesik** [comment]
is that issue up for grabs or anyone is already working on it ?

**Comment by ayusharma** [comment]
@pgrzesik Yes. this issue is up and you can start to working on it. :)

**Comment by juanpicado** [comment]
We need to define first what we are covering so the migration is clean.

**Comment by juanpicado** [comment]
@pgrzesik wanna work on it?

**Comment by sergiohgz** [comment]
@juanpicado did you think on moving to Travis-CI or prefer working on CircleCI? It would be a nice. I can study the upgrade before deadline or move to other alternative like Travis (I use several projects and understand something about how to build with it) :wink:

**Comment by juanpicado** [comment]
That would be cool  @sergiohgz ! The next week I'll add more detail about what we are doing now and what we need in 2.0 aside of migration.

**Comment by sergiohgz** [comment]
@juanpicado great, this week i can make a PR with the changes. It's pretty cool how workflows work (better than Jenkins Pipelines)

**Comment by juanpicado** [comment]
@sergiohgz update, please let me know if is clear or you need more information. You can find me around https://gitter.im/verdaccio/ as well.

**Comment by juanpicado** [comment]
Let's keep it open while I test a while.

**Comment by juanpicado** [comment]
Impressive job @sergiohgz  🥇 builds now are much faster than the previous configuration. 

![screen shot 2018-06-09 at 5 18 19 pm](https://user-images.githubusercontent.com/558752/41193171-2cea0dea-6c09-11e8-845e-a49d4146e5a8.png)

**Comment by sergiohgz** [comment]
Really nice to know an opinion about it. Caching across builders is so great, so I will use CircleCI in every project I can :smile:

**Comment by juanpicado** [comment]
Sorry, now I have bad news, something went wrong with the coverage.
![screen shot 2018-06-09 at 5 49 26 pm](https://user-images.githubusercontent.com/558752/41193521-82f0b596-6c0d-11e8-867e-1c9eaa3d3bc5.png)

**Comment by juanpicado** [comment]
Fixed the coverage 🚀 !! ... I'll test in the next days the deployment. Then we can close this ticket.

**Comment by juanpicado** [comment]
@sergiohgz deployment to `npm` did not work  :-( 

https://circleci.com/workflow-run/25119d3b-2931-49fe-b8e5-de29e1e631f1

**Comment by sergiohgz** [comment]
@juanpicado I am going to test that flow :wink:

**Comment by sergiohgz** [comment]
Reviewing that, I found two problems:
- Workflow was working only when pushing on branches, but not for tags
- This weird: [link](https://discuss.circleci.com/t/workflows-with-jobs-triggered-by-tag/18543/5). Basically, it says that builds triggered by tags will not be shown in workflows

The test I have done is trigger a release (failed because I haven't power to publish in registry) in my branch and examine the process of publishing:
- First weird thing: When you run `yarn release` and perform a `git push --follow-tags`, it launches two execution, one for _branch push event_ and other for _tag push event_
- Second weird thing (explained in CircleCI discussion forum): You won't see the _tag push_ triggered execution on Workflows view, but you can go to Builds view and look for that build that has no commit message

It looks better with an illustrated example:
- First I push commit on branch but not the tag. This means that **publish_package** step is not running on _branch push events_:
![branch push execution](https://user-images.githubusercontent.com/14012309/41279749-98143a34-6e2d-11e8-87b4-be0a2383f355.png)
- After a while, I push the tag to see if the **publish_package** step will run. Here we can see that it was executed (but I cancelled it before because I have no power to publish on registry):
![tag push execution](https://user-images.githubusercontent.com/14012309/41280124-76d9a150-6e2e-11e8-9406-0b40834645cd.png)
- A final image with the complete test is a great example:
![secuencial execution of push and tag events](https://user-images.githubusercontent.com/14012309/41280379-16a407de-6e2f-11e8-9479-14f045519544.png)
- The example is not complete without an image of the Workflows view, where we can see the _branch push execution_:
![workflow view](https://user-images.githubusercontent.com/14012309/41280509-67284666-6e2f-11e8-966e-663ddee389f4.png)


This doesn't means that you cannot push tag and 

I am going to remove that test from branch and create a PR :wink:

**Comment by juanpicado** [comment]
My branch has published a new website, I think the `ignore_branches` does not work proprely
```
 - publish_gh_pages:
          requires:
            - test_node6
            - test_node8
            - test_node9
            - test_node10
            - test_e2e
          <<: *ignore_branches
```

**Comment by sergiohgz** [comment]
Let me know the branch name and, if you remember, the build number in CircleCI, to see in which conditions it executed. Thanks

**Comment by juanpicado** [comment]
:-( it fails ... but from local works fine. I dunno whether is our fault. I just stopped to work for no reason.
https://codecov.io/gh/verdaccio/verdaccio/commits

**Comment by juanpicado** [comment]
@sergiohgz fixed the coverage. We just have pending the publish on npm issue.

**Comment by sergiohgz** [comment]
@juanpicado I have just tried to publish within my CircleCI and my npmjs account and it works well, I think it should work :wink:

**Comment by ayusharma** [comment]
@sergiohgz @juanpicado Great work here 👏
