### ISSUE TITLE
Fine line in ToS by using Verdaccio instead of NPM Enterprice?

### ISSUE THREAD

**Issue by helmutgranda** [verdaccio/verdaccio#652]
We are considering using Verdaccio for our company, however we are concerned of breaking any TOS. Is there a place where we can confidently say we are not breaking any rules set by NPM Enteprise?

https://www.npmjs.com/enterprise

**Comment by juanpicado** [comment]
Sorry, What TOS means?

**Comment by jbeard4** [comment]
Terms of Service

**Comment by helmutgranda** [comment]
Hi Juan,

I am reaching out to NPM directly to ensure we would not be breaking any rules, honestly I undestand NPM needs to make money to support their platform so it makes sense that they try their best to sell their Enterprise platform instead of just encouraging users to roll their own.

I just want to make sure the company I work for is protected if we were to make the recommendation to use verdaccio which BTW it is perfect for what we need.

**Comment by juanpicado** [comment]
Hi @helmutgranda 

> I am reaching out to NPM directly to ensure we would not be breaking any rules, honestly I undestand NPM needs to make money to support their platform so it makes sense that they try their best to sell their Enterprise platform instead of just encouraging users to roll their own.

I think many companies are using verdaccio with no fear, including previous companies I've worked on.

Furthermore, **I don't think you are breaking any rule using verdaccio on an enterprise environment** because verdaccio is not the unique solution available (but is the best one of course 😃 ) you can see this [similar things list](https://github.com/verdaccio/verdaccio/blob/2a51dbd40da58fe2318a0a4f6462d5938804bce9/README.md#similar-existing-things
). 

Also, npm provides a [Open Source Terms](https://github.com/npm/policies/blob/master/open-source-terms.md) to be better informed about their policies.

There are cloud platforms as Gemfury that they offer the same thing for free, Nexus is OSS and JFrog Artifactory even they charge for licenses to be able to use a npm registry. 

Since `v3` verdaccio is licensed as MIT https://github.com/verdaccio/verdaccio/issues/224 and if you are corcern about commercial usage you might read [here](https://www.quora.com/Can-you-use-software-under-MIT-licence-for-commercial-use) and also with such change we encorage companies to contribute verdaccio to keep it alive for long long long time.
 
If you still have corcerns about this topic you might ask directly to [Laurie Voss (here a npm enterprise slide talk)](https://youtu.be/zWEU8kNKi3Q?list=PLmAPAx5GNNtyTT5GvHPzbuBo-vWRte6g9&t=258) or file an issue [here https://github.com/npm/registry](https://github.com/npm/registry) where usually user ask about any registry issue.

> use verdaccio which BTW it is perfect for what we need.

I'm so glad to read that.

I hope my answer solve your doubts. If you have further questions let me know, otherwise, feel free to close the issue.

**Comment by helmutgranda** [comment]
Hi @juanpicado,

I heard back from NPM Sales team and I must say that they confirmed the assumption:

`Using Sinopia or Verdaccio doesn't break any rules or TOS`

There was more content in their email but in short that is what I was looking for. I must say that it is nice that they did not push their Enterprise platform but rather provide help and information.

Thanks again for creating this amazing tool!

**Comment by juanpicado** [comment]
I'm glad to hear that :) Enjoy Verdaccio ! Kudos to npm Inc !
