### ISSUE TITLE
Node versions deprecation

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/verdaccio#70]
Hi guys, 

As you may know, (https://github.com/nodejs/LTS) Node is gonna stop the LTS support for **0.10** at the end of the month and **0.12** at beginning of the next year. Node 4 also pretty soon will be dropped (**April 2017)**.  Basically they are force everybody to move Node 4 / 6 ASAP.

It does not make sense keep supporting such versions anymore, I think is time to move on and clean up a little bit, the code is getting old. I'm thinking, maybe move the code base to ES6 syntax is a good idea, after all is "completely" (97%) supported by Node 6 or Node 4 (52%) supported until 2018.

Aside of that I was thinking to re-do the front but for that I'd need mention this before. Waiting for your thoughts.

**Comment by trentearl** [comment]
@juanpicado Deprecating node versions sounds good.
I agree the code is getting old. For me, it makes it difficult to understand. I would like an es6 promise based architecture. I'm open to other ideas, especially because I dont currently have the time to put the work in.

The frontend could definitely use some work. It would be nice to have each package have its own page. I could definitely find time to work on this, but I havent yet thought about the design. Depending on what we came up with, I would probably want to move to react.

**Comment by juanpicado** [comment]
Yeah, I was working in a prototype just for fun, but then I saw the difficulty to use JSX with the current code base, I tried babel but some of lib files still use octal literals, since ES6 is strict mode by default it was my first stone on the road. About the front I'd move to React as well.

**Comment by juanpicado** [comment]
Solved here https://github.com/verdaccio/verdaccio/pull/115
