### ISSUE TITLE
proposal: also run tests on AppVeyor

### ISSUE THREAD

**Issue by DanielRuf** [verdaccio/verdaccio#796]
AppVeyor is for testing builds on Windows.

Would it make sense to add AppVeyor? Because there are often differences between Windows, macOS and Linux and it would be useful to test it on more.

**Comment by sergiohgz** [comment]
I think is not necessary to run tests on AppVeyor because, in short words, the app runs on top of NodeJs and browsers. The differences between systems comes from the implementation of those things in each system, not from the app. 

Also, I hear some things about AppVeyor but never use it. If you have more info about it, I would change my mind and give it a try 😉

**Comment by DanielRuf** [comment]
> The differences between systems comes from the implementation of those things in each system, not from the app

What about used (binary) dependencies? I can also run the tests on AppVeyor using my fork so we'll see if it makes to test it.

At least I saw issues and breaking unit tests on Windows (AppVeyor) in other projects.

**Comment by sergiohgz** [comment]
That's a great point. If you want you can contribute with it :wink:

**Comment by juanpicado** [comment]
Shoot ! @sergiohgz . Please create a simple config file then we can test the integration then.

**Comment by DanielRuf** [comment]
Let me know if you need any config examples.
