### ISSUE TITLE
add changelog info in package page

### ISSUE THREAD

**Issue by snadn** [verdaccio/verdaccio#813]
like yarnpkg.com show changelog info in package page

![image](https://user-images.githubusercontent.com/1269858/42683985-76bdfb8e-86c1-11e8-99b3-e1819114b777.png)

**Comment by Truemedia** [comment]
I think this would work well using the directories.doc directive https://docs.npmjs.com/files/package.json#directoriesdoc

So that you can specifiy in the package.json different MD files that you want to be displayed. Maybe you have not just a changelog, but a CONTRIBUTING.md and EXAMPLE.md, and they should be concatenated by verdaccio or given links on the page?

**Comment by snadn** [comment]
Yes, I think what I really care about is that there is a place on the page to display the changelog instead of the file name of the changelog.

**Comment by juanpicado** [comment]
To achieve such thing you need to keep on mind:
* Verdaccio does not unpack tarballs. It seems yarn uses under the hood (https://unpkg.com/verdaccio@3.2.0/) such service.
* Since we do not want to force the users to be online, the first point would be optional, never by default. But 👍 to have stuff.
* Verdaccio relies on metaadata that comes from external sources, (as readme), which it seems do not be available.

I do not have any possible solution of this on mind, but, let's see what others think.

**Comment by snadn** [comment]
i think provide a config is good

**Comment by DanielRuf** [comment]
And often these files can not be available in the package (npmignore).

**Comment by juanpicado** [comment]
yes, the package manager does not send this information, we don't unpack tarballs and as @DanielRuf just said, changelog is completely optional. I will close this one, we cannot do anything about it. If someone finds a way to achieve it with the current model, feel free to open a new discussion.
