### ISSUE TITLE
Improve docker image

### ISSUE THREAD

**Issue by sergiohgz** [verdaccio/verdaccio#836]
We have to review the Dockerfile and improve the size of each layers. Some examples of things to improve are:

- Remove **dumb-init**
- Remove the addition and elimination of **openssl** package
- Remove test on Dockerfile

**Comment by dlouzan** [comment]
We would like to build the verdaccio-gitlab image using as base the verdaccio one, but it will need some refactorings.

We experienced issues when deploying the image to openshift, since in there our admins have setup a policy of not allowing by default to run the container as root (pretty common setup), and openshift on top forces to run as a user with a random uid for security reasons. The [openshift guidelines](https://docs.openshift.org/latest/creating_images/guidelines.html#openshift-specific-guidelines) recommend to:
- setup a normal user to run under, that works on any environment, more or less what is being done right now
- setup permissions for the root group equal to the user permissions on the directories belonging the the app. When running in openshift, the container runs as a random, previously non-existing user that has no groups, and gets assigned the root group. The root group gets by default no special permissions.

You can see that the official postgres images are taking a similar approach to make the image runnable on any environment:
https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh

With these changes, we would be able to base our image on verdaccio's and add the plugin to the APPDIR. Otherwise, when running in openshift, the verdaccio user does not have write access to the APPDIR.

I'm currently experimenting in my own branch under:  
https://github.com/dlouzan/verdaccio-gitlab/tree/refactor-docker-random-guid

/cc @bufferoverflow @ercanucan

**Comment by dlouzan** [comment]
Another option (not exclusive to this) is to be able to pass a location for the plugins directory and then set that up on the helm chart configuration as volume.

But for users I think it's easier if we can provide images including the appropriate plugins, instead of having to put their plugins on external volumes.

**Comment by dlouzan** [comment]
Regarding dumb-init, I think we still need to ensure that an appropriate init system is used. Per [node's official documentation](https://github.com/nodejs/docker-node/blob/master/docs/BestPractices.md#handling-kernel-signals), node's handling of kernel signals is far from perfect.

The issue with the native support with docker's `--init` option (which is based on tini), is that this is only enforced when using the docker cli. I haven't found a way to enforce that on k8s/openshift, so might be in the situation that users are responsible for starting with the right flags when using docker directly, and no way to pass that information when run in k8s. I think a lose/lose situation. Just enforce it on the image itself like it is done now, the init wrapper has no downsides.

We could migrate to tini if you see a clear advantage, but otherwise, I'd stay with dumb-init. One could argue that the native support in docker is based on tini, so we should use it explicitly.

**Comment by juanpicado** [comment]
> Another option (not exclusive to this) is to be able to pass a location for the plugins directory and then set that up on the helm chart configuration as volume.

I think we are doing that already https://github.com/verdaccio/docker-examples/blob/master/docker-plugin-external/docker-compose.yml or you meant something different?

**Comment by dlouzan** [comment]
I had seen a couple of days ago that there was a PR ongoing for that option, but I didn't know it was already merged :-D

**Comment by dlouzan** [comment]
Soooo, I think I have a pretty good state right now with the Dockerfile refactoring. I worked at the same time on the verdaccio and verdaccio-gitlab repos, and tested this on my local env and an openshift cluster.

Summary of design / changes:

- The build is broken into a multistage setup, with a builder image and a final image in which we copy the generated artifacts. This reduces the size of the image from ~500 MB to ~125 MB (the sizes as reported by the docker hub [are wrong](https://github.com/docker/hub-feedback/issues/331))
- dumb-init is kept for the reasons outlined above in my comments
- Following the same approach as the helm chart, the only volume exposed is the storage, under a `/verdaccio/storage/data` subdir in the default config, that allows to separate that from data written by other plugins (e.g. htpasswd)
- The code is written to `/opt/verdaccio`; the `verdaccio` run user cannot modify the compiled resources nor config, only the `/verdaccio/storage` volume
- Follow the [recommended OpenShift approach](https://docs.openshift.com/enterprise/3.0/creating_images/guidelines.html#openshift-specific-guidelines) for making a non-user image runnable on vanilla k8s & openshift:
  - force a specific uid `10001` for the run user, assign the `root` group to the locations that need to be written by the run user; if running in a normal environment, the specific id is used and permissions are correct; if running on a randomized uid environment like openshift, the non-existent user gets assigned the root group and allowed write access to relevant locations
  - add an entrypoint that will add the user to `/etc/passwd` in case the user is running as a random uid (openshift). That way, the typical tools like `whoami` and so can still work. [postgres takes a similar approach](https://github.com/docker-library/postgres/blob/master/docker-entrypoint.sh) using nss_wrapper

I'm not sure about this involving breaking changes (maybe the uid of the user), but I tried to follow the same approach as in the helm chart. I also applied similar ideas as contained on https://github.com/verdaccio/verdaccio/pull/845

You guys please let me know how to proceed, should I open a PR for review, do you want to take a look at the source branches...?

The work is here:
https://github.com/dlouzan/verdaccio/tree/refactor/dockerfile-random-uid-support
https://github.com/dlouzan/verdaccio-gitlab/tree/refactor-docker-random-guid

/cc @ercanucan @bufferoverflow

**Comment by dlouzan** [comment]
I forgot to mention: in the other image verdaccio-gitlab created based on this, I'm using the same approach: multistage build with a compile of the sources, then use an image based on verdaccio to copy the artifacts.

The data is stored in `/opt/verdaccio-gitlab`, and then the plugin is loaded by using the new support for referencing a plugins directory by symlinking `/opt/verdaccio-gitlab` under `/verdaccio/plugins/verdaccio-gitlab`.

**Comment by juanpicado** [comment]
@dlouzan amazing 💯 ... I'll wait for others feedback. But I like the approach by far.

**Comment by bufferoverflow** [comment]
@dlouzan awesome! Could you create pull requests, so we can discuss within the code?

**Comment by dlouzan** [comment]
Created #864

**Comment by juanpicado** [comment]
<img width="802" alt="verdaccio_verdaccio_-_docker_hub" src="https://user-images.githubusercontent.com/558752/43949150-fb6fce94-9c8c-11e8-9289-664270f7c489.png">

**Comment by dlouzan** [comment]
[It's actually bigger than that](https://github.com/docker/hub-feedback/issues/331), but so were the previous images. In my computer docker says:

```
verdaccio/verdaccio          4.x-next        fb5088c9507f        15 hours ago        125MB
verdaccio/verdaccio          3.5.1           bedb9a1f76f3        8 days ago          686MB
```

**Comment by juanpicado** [comment]
I was using Kinetics and I just noticed I cannot modify the other volumes from here and reading the Dockfile ...

```
VOLUME /verdaccio/storage
```
I wonder, what's happen with `/verdaccio/plugins /verdaccio/conf` then? how could overwrite it from such UI tool?

![screen shot 2018-09-08 at 10 10 22 am](https://user-images.githubusercontent.com/558752/45251973-69959880-b34f-11e8-89a4-7a83ea11b392.png)

**Comment by dlouzan** [comment]
Hello Juan, the idea is that the storage directory is loaded as a named volume, which guarantees write rights plus persistency between restarts. The other two directories are mounted as read-only to user verdaccio on startup, since it's not the idea that you modify them at runtime (why would we?).

I'm not familiar with kinematic, but the idea would be the same as done in kubernetes / helm: in order to modify the configuration, you mount on startup a file or directory with the appropriate configuration, and you either overwrite exactly those paths, or you can even modify the startup command to point to e.g. another configuration file. You don't need a volume, but with volumes it will also work.

I can only imagine that kinematic provides a similar functionality, the capability has existed in docker for a long time.

**Comment by juanpicado** [comment]
Thanks @dlouzan for the wide explanation 😃

**Comment by dlouzan** [comment]
I'll be working on the improved documentation next week

**Comment by juanpicado** [comment]
As a reminder, the doc was moved here => https://github.com/verdaccio/website

**Comment by juanpicado** [comment]
I running https://github.com/replicatedhq/dockerfilelint on the `4.x` image and I'm getting the following. I'd love your opinion @sergiohgz @dlouzan 
```
Digest: sha256:45951c9f51720b6fcc13258197c3fe74ef782dbe9a9021bccd4a4b8e52728945
Status: Downloaded newer image for replicated/dockerfilelint:latest

File:   Dockerfile
Issues: 2

Line 6: RUN apk --no-cache add openssl ca-certificates wget && \
Issue  Category      Title                 Description
    1  Optimization  Consider `--no-cache  Consider using a `--no-cache` (supported in alpine linux >= 3.3) or
                     or --update with rm   `--update` followed by the command `rm -rf /var/cache/apk/*` when
                     -rf                   `apk` adding packages.  This will result in a smaller image size.
                     /var/cache/apk/*`     For
                                           more information, see [this
                                           link](https://github.com/gliderlabs/docker-alpine/blob/master/docs/
                                           usage.md)

Line 53: EXPOSE $VERDACCIO_PORT
Issue  Category      Title                 Description
    2  Possible Bug  Invalid Port Exposed  Exposing ports should only be valid port numbers.

### FAILED Docker Lint 19:12:03Z (26.435s)
```

**Comment by dlouzan** [comment]
The issue in line 6 can be done, no harm at all, will make the image smaller which is always a good thing.

The one on line 53 is a bit weird, seems the linter cannot resolve references to env variables defined earlier and thus thinks that the port is incorrect (there's in fact an open issue for it https://github.com/replicatedhq/dockerfilelint/issues/86).

**Comment by juanpicado** [comment]
@dlouzan when you have time perhaps you can check whether this Docker migration guide is good enough or we should add something else

https://verdaccio.org/blog/2019/02/24/migrating-verdaccio#migrating-from-verdaccio-3x-to-verdaccio-4x

**Comment by dlouzan** [comment]
@juanpicado For the moment looks good :-) I would suggest, as we approach v4 release, maybe when you plan to start beta testing, I'd like to perform some migration tests on my end, manually setting up an v3 server and doing the migration to v4, to make sure nothing is left out. In particular, I'd like to test if the existing storage vs docker volumes shows no issues.

Just ping me when we are close and I'd take care of it.

**Comment by juanpicado** [comment]
@dlouzan thanks for checking this out :-) I'll merge 4.x today, so, next step is launch beta on 15th April.   That day we will start beta testing and nothing will be added for 1 month until 15th May final release. Let me know if you find something 👍 

The tag `4.x-next` will remains the same, no changes.

**Comment by dlouzan** [comment]
Ok, I'll make a note and try to perform the tests (ideally also automate them somehow in code) before April 15th.

**Comment by dlouzan** [comment]
@bufferoverflow FYI, verdaccio 4 beta starts on April 15th

**Comment by juanpicado** [comment]
btw, 15th April, is Verdaccio birthday 🍰 🎉  ... 
![](https://media.giphy.com/media/xT0BKqxuUDfosKEXXG/giphy.gif)
