### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by pfdgithub** [verdaccio/verdaccio#877]
**Describe the bug**
verdaccio 3.4.1  
An error is thrown when the uplinks requests timeout:  
Error: Can't set headers after they are sent.  

**To Reproduce**
1. An unstable network
2. npm i fsevents (or other package?)
3. Error: ESOCKETTIMEDOUT (no relevance?)
4. Error: Can't set headers after they are sent.

**Expected behavior**
Response the uplinks error message.  

**Cleaned error stack**
```
Error: Can't set headers after they are sent.
at validateHeader (_http_outgoing.js:491:11)
at ServerResponse.setHeader (_http_outgoing.js:498:3)
at ServerResponse.header (/usr/lib/node_modules/verdaccio/node_modules/express/lib/response.js:767:10)
at ServerResponse.send (/usr/lib/node_modules/verdaccio/node_modules/express/lib/response.js:170:12)
at final (/usr/lib/node_modules/verdaccio/build/api/middleware.js:181:7)
at /usr/lib/node_modules/verdaccio/build/api/index.js:130:14
at ServerResponse.res.report_error (/usr/lib/node_modules/verdaccio/build/api/middleware.js:275:9)
```

**Mapping source**
```
https://github.com/expressjs/express/blob/4.16.3/lib/response.js#L767
https://github.com/expressjs/express/blob/4.16.3/lib/response.js#L170
https://github.com/verdaccio/verdaccio/blob/v3.4.1/src/api/middleware.js#L165
https://github.com/verdaccio/verdaccio/blob/v3.4.1/src/api/index.js#L103
https://github.com/verdaccio/verdaccio/blob/v3.4.1/src/api/middleware.js#L260
```

**Original error stack**
```
error--- unexpected error: ESOCKETTIMEDOUT
Error: ESOCKETTIMEDOUT
at ClientRequest.<anonymous> (/usr/lib/node_modules/verdaccio/node_modules/request/request.js:812:19)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at ClientRequest.emit (events.js:208:7)
at TLSSocket.emitTimeout (_http_client.js:706:34)
at Object.onceWrapper (events.js:313:30)
at emitNone (events.js:106:13)
at TLSSocket.emit (events.js:208:7)
at TLSSocket.Socket._onTimeout (net.js:410:8)
at ontimeout (timers.js:498:11)
at tryOnTimeout (timers.js:323:5)
at Timer.listOnTimeout (timers.js:290:5)
http <-- 500, user: xxx(xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx via xxx.xxx.xxx.xxx), req: 'GET /fsevents/-/fsevents-1.2.4.tgz', error: content length mismatch
Error: Can't set headers after they are sent.
at validateHeader (_http_outgoing.js:491:11)
at ServerResponse.setHeader (_http_outgoing.js:498:3)
at ServerResponse.header (/usr/lib/node_modules/verdaccio/node_modules/express/lib/response.js:767:10)
at ServerResponse.send (/usr/lib/node_modules/verdaccio/node_modules/express/lib/response.js:170:12)
at final (/usr/lib/node_modules/verdaccio/build/api/middleware.js:181:7)
at Layer.handle_error (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:315:13)
at /usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:335:12)
at next (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:275:10)
at /usr/lib/node_modules/verdaccio/build/api/index.js:130:14
at Layer.handle_error (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:71:5)
at trim_prefix (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:315:13)
at /usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:335:12)
at next (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:275:10)
at Layer.handle_error (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/layer.js:67:12)
at trim_prefix (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:315:13)
at /usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:284:7
at Function.process_params (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:335:12)
at next (/usr/lib/node_modules/verdaccio/node_modules/express/lib/router/index.js:275:10)
at ServerResponse.res.report_error (/usr/lib/node_modules/verdaccio/build/api/middleware.js:275:9)
```

**Comment by mattdsteele** [comment]
Here's some more logs from verdaccio set with `NODE_DEBUG=request`, when I run `npm i jquery` against it:

<details>
  <summary>Request log</summary>
<pre><code>
 http <-- 200, user: undefined(167.132.98.27), req: 'GET /jquery', bytes: 0/11217
REQUEST { url: 'https://registry.npmjs.org/-/npm/v1/security/audits',
  method: 'POST',
  req:
   IncomingMessage {
     _readableState:
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: false,
        ended: true,
        endEmitted: true,
        reading: false,
        sync: false,
        needReadable: false,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: { data: [Function], close: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 18968,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [Object],
        _peername: [Object],
        [Symbol(asyncId)]: 58,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 59,
        [Symbol(triggerAsyncId)]: 58 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 18968,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [Object],
        _peername: [Object],
        [Symbol(asyncId)]: 58,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 59,
        [Symbol(triggerAsyncId)]: 58 },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers:
      { connection: 'keep-alive',
        'user-agent': 'npm/6.3.0 node/v8.11.1 win32 x64',
        'npm-in-ci': 'false',
        'npm-scope': '',
        'npm-session': 'd8f1a61704570ff9',
        referer: 'undefined',
        'content-encoding': 'gzip',
        'content-type': 'application/json',
        accept: '*/*',
        'content-length': '193',
        'accept-encoding': 'gzip,deflate',
        host: 'https://registry.npmjs.org/' },
     rawHeaders:
      [ 'connection',
        'keep-alive',
        'user-agent',
        'npm/6.3.0 node/v8.11.1 win32 x64',
        'npm-in-ci',
        'false',
        'npm-scope',
        '',
        'npm-session',
        'd8f1a61704570ff9',
        'referer',
        'undefined',
        'content-encoding',
        'gzip',
        'content-type',
        'application/json',
        'content-type',
        'application/octet-stream',
        'accept',
        '*/*',
        'content-length',
        '193',
        'accept-encoding',
        'gzip,deflate',
        'Host',
        'omhqv1361e.uprr.com:4873' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '/audits/quick',
     method: 'POST',
     statusCode: null,
     statusMessage: null,
     client:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 10,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: true,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: [Object],
        _server: [Object],
        _idleTimeout: 120000,
        _idleNext: [Object],
        _idlePrev: [Object],
        _idleStart: 18968,
        _destroyed: false,
        parser: [Object],
        on: [Function: socketOnWrap],
        _paused: false,
        read: [Function],
        _consuming: true,
        _httpMessage: [Object],
        _peername: [Object],
        [Symbol(asyncId)]: 58,
        [Symbol(bytesRead)]: 0,
        [Symbol(asyncId)]: 59,
        [Symbol(triggerAsyncId)]: 58 },
     _consuming: true,
     _dumped: false,
     next: [Function: next],
     baseUrl: '/-/npm/v1/security',
     originalUrl: '/-/npm/v1/security/audits/quick',
     _parsedUrl:
      Url {
        protocol: null,
        slashes: null,
        auth: null,
        host: null,
        port: null,
        hostname: null,
        hash: null,
        search: null,
        query: null,
        pathname: '/audits/quick',
        path: '/audits/quick',
        href: '/audits/quick',
        _raw: '/audits/quick' },
     params: {},
     query: {},
     res:
      ServerResponse {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: false,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: true,
        sendDate: true,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: false,
        _headerSent: false,
        socket: [Object],
        connection: [Object],
        _header: null,
        _onPendingData: [Function: bound updateOutgoingData],
        _sent100: false,
        _expect_continue: false,
        req: [Circular],
        locals: {},
        write: [Function: write],
        end: [Function: end],
        report_error: [Function],
        writeHead: [Function: writeHead],
        flush: [Function: flush],
        on: [Function: on],
        [Symbol(outHeadersKey)]: [Object] },
     log:
      Logger {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        _level: 35,
        streams: [Array],
        serializers: [Object],
        src: false,
        fields: [Object] },
     body:
      { requires: [Object],
        dependencies: [Object],
        install: [Array],
        remove: [],
        metadata: [Object] },
     _body: true,
     read: [Function],
     route: Route { path: '/audits/quick', stack: [Array], methods: [Object] } },
  body: '{"requires":{"jquery":"^3.3.1"},"dependencies":{"jquery":{"version":"3.3.1","integrity":"sha1-lYzinoHJeQ8xvneS311NlfxX+8o="}},"install":["jquery@3.3.1"],"remove":[],"metadata":{"npm_version":"6.3.0","node_version":"v8.11.1","platform":"win32"}}',
  gzip: true,
  strictSSL: true,
  callback: [Function: requestCallback] }
REQUEST make request https://registry.npmjs.org/-/npm/v1/security/audits
REQUEST { url: 'https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz',
  method: 'GET',
  headers:
   { Accept: 'application/json;',
     'Accept-Encoding': 'gzip',
     'User-Agent': 'npm (verdaccio/3.5.1)',
     Via: '1.1 4ab856a8fcbf (Verdaccio)' },
  encoding: null,
  gzip: true,
  timeout: 30000,
  strictSSL: true,
  callback: undefined }
REQUEST make request https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz
REQUEST onRequestResponse https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz 200 { date: 'Wed, 08 Aug 2018 18:44:01 GMT',
  server: 'Artifactory/5.10.3',
  'x-artifactory-id': 'c30034f061bf67cb:5ff8da89:163564c61bb:-8000',
  'last-modified': 'Fri, 25 May 2018 10:41:50 GMT',
  etag: '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha1': '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha256': '2c7c70a1e796c1568ff05d45a8cb2da2a0fc6e37426c65e4eef6ee55e217933e',
  'x-checksum-md5': 'b7622e0bf3321da7e8fa42c692af596d',
  'accept-ranges': 'bytes',
  'x-artifactory-filename': 'jquery-3.3.1.tgz',
  'content-disposition': 'attachment; filename="jquery-3.3.1.tgz"; filename*=UTF-8\'\'jquery-3.3.1.tgz',
  'content-type': 'application/x-gzip',
  'content-length': '415379',
  'set-cookie':
   [ 'wt_up=167.132.90.21.1533753841100675; path=/; expires=Fri, 07-Aug-20 18:44:01 GMT; domain=.uprr.com' ],
  webserver_id: 'dx1daa',
  upenv: 'int',
  connection: 'close',
  'content-encoding': 'gzip' }
REQUEST finish init function https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz
 http <-- 200, user: undefined(167.132.98.27), req: 'GET /jquery/-/jquery-3.3.1.tgz', bytes: 0/845842
REQUEST onRequestResponse https://registry.npmjs.org/-/npm/v1/security/audits 200 { date: 'Wed, 08 Aug 2018 18:44:01 GMT',
  'content-type': 'application/json; charset=utf-8',
  'transfer-encoding': 'chunked',
  connection: 'close',
  'set-cookie':
   [ '__cfduid=d4ebdcd6b929756e9023d861c4cadc5761533753841; expires=Thu, 08-Aug-19 18:44:01 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
  'content-encoding': 'gzip',
  'access-control-allow-credentials': 'true',
  'access-control-allow-origin': '*',
  'cf-ray': '447421c33e0a552e-ORD',
  'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  server: 'cloudflare' }
REQUEST reading response's body
REQUEST finish init function https://registry.npmjs.org/-/npm/v1/security/audits
REQUEST response end https://registry.npmjs.org/-/npm/v1/security/audits 200 { date: 'Wed, 08 Aug 2018 18:44:01 GMT',
  'content-type': 'application/json; charset=utf-8',
  'transfer-encoding': 'chunked',
  connection: 'close',
  'set-cookie':
   [ '__cfduid=d4ebdcd6b929756e9023d861c4cadc5761533753841; expires=Thu, 08-Aug-19 18:44:01 GMT; path=/; domain=.registry.npmjs.org; HttpOnly' ],
  'content-encoding': 'gzip',
  'access-control-allow-credentials': 'true',
  'access-control-allow-origin': '*',
  'cf-ray': '447421c33e0a552e-ORD',
  'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
  server: 'cloudflare' }
REQUEST end event https://registry.npmjs.org/-/npm/v1/security/audits
REQUEST has body https://registry.npmjs.org/-/npm/v1/security/audits 210
REQUEST emitting complete https://registry.npmjs.org/-/npm/v1/security/audits
 http <-- 200, user: undefined(167.132.98.27), req: 'POST /-/npm/v1/security/audits/quick', bytes: 193/210
REQUEST { url: 'https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz',
  method: 'GET',
  headers:
   { Accept: 'application/json;',
     'Accept-Encoding': 'gzip',
     'User-Agent': 'npm (verdaccio/3.5.1)',
     Via: '1.1 4ab856a8fcbf (Verdaccio)' },
  encoding: null,
  gzip: true,
  timeout: 30000,
  strictSSL: true,
  callback: undefined }
REQUEST make request https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz
REQUEST onRequestResponse https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz 200 { date: 'Wed, 08 Aug 2018 18:44:02 GMT',
  server: 'Artifactory/5.10.3',
  'x-artifactory-id': 'c30034f061bf67cb:5ff8da89:163564c61bb:-8000',
  'last-modified': 'Fri, 25 May 2018 10:41:50 GMT',
  etag: '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha1': '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha256': '2c7c70a1e796c1568ff05d45a8cb2da2a0fc6e37426c65e4eef6ee55e217933e',
  'x-checksum-md5': 'b7622e0bf3321da7e8fa42c692af596d',
  'accept-ranges': 'bytes',
  'x-artifactory-filename': 'jquery-3.3.1.tgz',
  'content-disposition': 'attachment; filename="jquery-3.3.1.tgz"; filename*=UTF-8\'\'jquery-3.3.1.tgz',
  'content-type': 'application/x-gzip',
  'content-length': '415379',
  'set-cookie':
   [ 'wt_up=167.132.90.21.1533753842294312; path=/; expires=Fri, 07-Aug-20 18:44:02 GMT; domain=.uprr.com' ],
  webserver_id: 'dx1daa',
  upenv: 'int',
  connection: 'close',
  'content-encoding': 'gzip' }
REQUEST finish init function https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz
 http <-- 200, user: undefined(167.132.98.27), req: 'GET /jquery/-/jquery-3.3.1.tgz', bytes: 0/731564
 error--- unexpected error: ESOCKETTIMEDOUT
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/upapps/uit/ver/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
REQUEST response end https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz 200 { date: 'Wed, 08 Aug 2018 18:44:01 GMT',
  server: 'Artifactory/5.10.3',
  'x-artifactory-id': 'c30034f061bf67cb:5ff8da89:163564c61bb:-8000',
  'last-modified': 'Fri, 25 May 2018 10:41:50 GMT',
  etag: '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha1': '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha256': '2c7c70a1e796c1568ff05d45a8cb2da2a0fc6e37426c65e4eef6ee55e217933e',
  'x-checksum-md5': 'b7622e0bf3321da7e8fa42c692af596d',
  'accept-ranges': 'bytes',
  'x-artifactory-filename': 'jquery-3.3.1.tgz',
  'content-disposition': 'attachment; filename="jquery-3.3.1.tgz"; filename*=UTF-8\'\'jquery-3.3.1.tgz',
  'content-type': 'application/x-gzip',
  'content-length': '415379',
  'set-cookie':
   [ 'wt_up=167.132.90.21.1533753841100675; path=/; expires=Fri, 07-Aug-20 18:44:01 GMT; domain=.uprr.com' ],
  webserver_id: 'dx1daa',
  upenv: 'int',
  connection: 'close',
  'content-encoding': 'gzip' }
REQUEST aborted https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/upapps/uit/ver/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/upapps/uit/ver/node_modules/express/lib/response.js:170:12)
    at final (/upapps/uit/ver/node_modules/verdaccio/build/api/middleware.js:181:7)
    at Layer.handle_error (/upapps/uit/ver/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/upapps/uit/ver/node_modules/express/lib/router/index.js:315:13)
    at /upapps/uit/ver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/upapps/uit/ver/node_modules/express/lib/router/index.js:335:12)
    at next (/upapps/uit/ver/node_modules/express/lib/router/index.js:275:10)
 error--- unexpected error: ESOCKETTIMEDOUT
Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/upapps/uit/ver/node_modules/request/request.js:812:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at TLSSocket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at TLSSocket.emit (events.js:208:7)
    at TLSSocket.Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
REQUEST response end https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz 200 { date: 'Wed, 08 Aug 2018 18:44:02 GMT',
  server: 'Artifactory/5.10.3',
  'x-artifactory-id': 'c30034f061bf67cb:5ff8da89:163564c61bb:-8000',
  'last-modified': 'Fri, 25 May 2018 10:41:50 GMT',
  etag: '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha1': '958ce29e81c9790f31be7792df5d4d95fc57fbca',
  'x-checksum-sha256': '2c7c70a1e796c1568ff05d45a8cb2da2a0fc6e37426c65e4eef6ee55e217933e',
  'x-checksum-md5': 'b7622e0bf3321da7e8fa42c692af596d',
  'accept-ranges': 'bytes',
  'x-artifactory-filename': 'jquery-3.3.1.tgz',
  'content-disposition': 'attachment; filename="jquery-3.3.1.tgz"; filename*=UTF-8\'\'jquery-3.3.1.tgz',
  'content-type': 'application/x-gzip',
  'content-length': '415379',
  'set-cookie':
   [ 'wt_up=167.132.90.21.1533753842294312; path=/; expires=Fri, 07-Aug-20 18:44:02 GMT; domain=.uprr.com' ],
  webserver_id: 'dx1daa',
  upenv: 'int',
  connection: 'close',
  'content-encoding': 'gzip' }
REQUEST aborted https://privatedomain.com/artifactory/api/npm/npmjs/jquery/-/jquery-3.3.1.tgz?dl=https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at ServerResponse.setHeader (_http_outgoing.js:498:3)
    at ServerResponse.header (/upapps/uit/ver/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/upapps/uit/ver/node_modules/express/lib/response.js:170:12)
    at final (/upapps/uit/ver/node_modules/verdaccio/build/api/middleware.js:181:7)
    at Layer.handle_error (/upapps/uit/ver/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/upapps/uit/ver/node_modules/express/lib/router/index.js:315:13)
    at /upapps/uit/ver/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/upapps/uit/ver/node_modules/express/lib/router/index.js:335:12)
    at next (/upapps/uit/ver/node_modules/express/lib/router/index.js:275:10)
</code></pre>
</details>

I'm not sure if the issue is with Artifactory or Verdaccio; any ideas what might be occurring?

**Comment by juanpicado** [comment]
I've been looking into this error and I found a couple of things which might be better. I don't expect changes on `v3` but pretty likely I will refactor this to handle properly this errors.

To give more context about what I've seen. `error--- unexpected error: ESOCKETTIMEDOUT` means the stream opened in order to fetch the file has failed for external reasons. But the logic to retry was never intended to handle streaming files, only fetch metadata. So in case, the stream fails like the scenario above, it just displays a nasty error.

Frankly, I could not reproduce `Error: Can't set headers after they are sent.` but I'm still trying.

**Comment by zsubzwary** [comment]
I am having exact same issue...

@juanpicado to reproduce just follow these:
1. Delete all files from storage to clear cache
2. Then connect your PC to a Crappy Internet _(which has a very slow speed or is constantly disconnected)_
3. Then run the command for creating a new project !!
---
BTW my error output was as follow: 👇  👇 

```
http <-- 200, user: null(127.0.0.1), req: 'GET /@types%2fvfile-message/-/vfile-message-1.0.1.tgz', bytes: 0/2111
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\response.js:767:10)
    at ServerResponse.send (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\response.js:170:12)
    at final (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\build\api\middleware.js:181:7)
    at Layer.handle_error (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\router\layer.js:71:5)
    at trim_prefix (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\router\index.js:315:13)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\node_modules\express\lib\router\index.js:275:10)
    at C:\Users\USERNAME\AppData\Roaming\npm\node_modules\verdaccio\build\api\index.js:130:14
```

**Comment by lal12** [comment]
I have the same issue. After some downloads there occurs a `ESOCKETTIMEDOUT`. Afterwards it does not seem to recover and always says `error: uplink is offline`, while the client receives error 500. Might the issue be about the ´uplink down` flag/state not being checked (reconnected) again?

**Comment by swistaczek** [comment]
Hey, I have the same issue :( - `Can't set headers after they are sent`

**Comment by juanpicado** [comment]
Would be really useful if all of you describe in which conditions this happens. It happened to me like twice in one year but I barely remember how to reproduce it. Would be great for a triage see a few steps that easily help to dive more into this.

**Comment by cobolbaby** [comment]
+1

**Comment by juanpicado** [comment]
hi guys, if there is no reproducible steps I hardly will dive into this. I tried steps above and I cannot reproduce.

**Comment by lal12** [comment]
> hi guys, if there is no reproducible steps I hardly will dive into this. I tried steps above and I cannot reproduce.

Unfortunately there aren't. Just sometimes (like at most 1/2weeks) this occurs especially after installing many packages for e.g. a huge project. Maybe you could try to let a http request for a packet (from verdaccio to npm) fail with a proxy and look if this will reproduce it. But apart from that not really any clue under what circumstances this happens.

**Comment by Baoyx007** [comment]
same issue

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/usr/local/share/.config/yarn/global/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/usr/local/share/.config/yarn/global/node_modules/express/lib/response.js:170:12)
    at final (/usr/local/share/.config/yarn/global/node_modules/verdaccio/build/api/middleware.js:199:7)
    at Layer.handle_error (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:315:13)
    at /usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/local/share/.config/yarn/global/node_modules/express/lib/router/index.js:275:10)
    at /usr/local/share/.config/yarn/global/node_modules/verdaccio/build/api/index.js:108:14
```

**Comment by DanielRuf** [comment]
Which version of verdaccio do you use @Baoyx007?

**Comment by Baoyx007** [comment]
4.2.2

**Comment by juanpicado** [comment]
Trying to reproduce this over test https://github.com/verdaccio/verdaccio/pull/1959 , no much luck yet, but maybe @Baoyx007 is right and moving `res.send(body);` actually solves the issue.
